//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGroup : Entity
    {
        public AccountGroup()
        {
            this.AccountInGroups = new HashSet<AccountInGroup>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    
    	private ICollection<AccountInGroup> _accountingroups;
        public virtual ICollection<AccountInGroup> AccountInGroups { get { return _accountingroups; } set { SetNotifyingProperty(ref _accountingroups, value); } }
    }
}
