//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGoodTran : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private System.DateTime _createddate;
        public System.DateTime CreatedDate { get { return _createddate; } set { SetNotifyingProperty(ref _createddate, value); } }
    	private int _stockid;
        public int StockID { get { return _stockid; } set { SetNotifyingProperty(ref _stockid, value); } }
    	private int _goodid;
        public int GoodID { get { return _goodid; } set { SetNotifyingProperty(ref _goodid, value); } }
    	private Nullable<int> _quantity;
        public Nullable<int> Quantity { get { return _quantity; } set { SetNotifyingProperty(ref _quantity, value); } }
    	private Nullable<double> _price;
        public Nullable<double> Price { get { return _price; } set { SetNotifyingProperty(ref _price, value); } }
    	private int _accountid;
        public int AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private Nullable<double> _debit;
        public Nullable<double> Debit { get { return _debit; } set { SetNotifyingProperty(ref _debit, value); } }
    	private Nullable<double> _credit;
        public Nullable<double> Credit { get { return _credit; } set { SetNotifyingProperty(ref _credit, value); } }
    	private int _type;
        public int Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    }
}
