//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTran : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private Nullable<int> _accountid;
        public Nullable<int> AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private Nullable<int> _accounttype;
        public Nullable<int> AccountType { get { return _accounttype; } set { SetNotifyingProperty(ref _accounttype, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<System.DateTime> _date;
        public Nullable<System.DateTime> Date { get { return _date; } set { SetNotifyingProperty(ref _date, value); } }
    	private string _reference;
        public string Reference { get { return _reference; } set { SetNotifyingProperty(ref _reference, value); } }
    	private Nullable<double> _spent;
        public Nullable<double> Spent { get { return _spent; } set { SetNotifyingProperty(ref _spent, value); } }
    	private Nullable<double> _received;
        public Nullable<double> Received { get { return _received; } set { SetNotifyingProperty(ref _received, value); } }
    	private Nullable<int> _amountare;
        public Nullable<int> AmountAre { get { return _amountare; } set { SetNotifyingProperty(ref _amountare, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private Nullable<int> _type;
        public Nullable<int> Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    	private Nullable<int> _bankaccountid;
        public Nullable<int> BankAccountID { get { return _bankaccountid; } set { SetNotifyingProperty(ref _bankaccountid, value); } }
    	private Nullable<int> _companyid;
        public Nullable<int> CompanyID { get { return _companyid; } set { SetNotifyingProperty(ref _companyid, value); } }
    	private Nullable<int> _sourceid;
        public Nullable<int> SourceID { get { return _sourceid; } set { SetNotifyingProperty(ref _sourceid, value); } }
    	private Nullable<int> _sourcetype;
        public Nullable<int> SourceType { get { return _sourcetype; } set { SetNotifyingProperty(ref _sourcetype, value); } }
    	private string _transactionname;
        public string TransactionName { get { return _transactionname; } set { SetNotifyingProperty(ref _transactionname, value); } }
    	private Nullable<int> _method;
        public Nullable<int> Method { get { return _method; } set { SetNotifyingProperty(ref _method, value); } }
    
    	private Company _company;
        public virtual Company Company { get { return _company; } set { SetNotifyingProperty(ref _company, value); } }
    	private BankAccount _bankaccount;
        public virtual BankAccount BankAccount { get { return _bankaccount; } set { SetNotifyingProperty(ref _bankaccount, value); } }
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    }
}
