//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBalance : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _accountid;
        public int AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private double _debit;
        public double Debit { get { return _debit; } set { SetNotifyingProperty(ref _debit, value); } }
    	private double _credit;
        public double Credit { get { return _credit; } set { SetNotifyingProperty(ref _credit, value); } }
    
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    }
}
