//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInGroup : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _accountgroupid;
        public int AccountGroupID { get { return _accountgroupid; } set { SetNotifyingProperty(ref _accountgroupid, value); } }
    	private int _accountid;
        public int AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    
    	private AccountGroup _accountgroup;
        public virtual AccountGroup AccountGroup { get { return _accountgroup; } set { SetNotifyingProperty(ref _accountgroup, value); } }
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    }
}
