//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType : Entity
    {
        public AccountType()
        {
            this.Accounts = new HashSet<Account>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private Nullable<int> _type;
        public Nullable<int> Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    	private int _parentid;
        public int ParentID { get { return _parentid; } set { SetNotifyingProperty(ref _parentid, value); } }
    
    	private ICollection<Account> _accounts;
        public virtual ICollection<Account> Accounts { get { return _accounts; } set { SetNotifyingProperty(ref _accounts, value); } }
    }
}
