//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBudgetTran : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _budgetid;
        public int BudgetID { get { return _budgetid; } set { SetNotifyingProperty(ref _budgetid, value); } }
    	private int _accountid;
        public int AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private Nullable<System.DateTime> _date;
        public Nullable<System.DateTime> Date { get { return _date; } set { SetNotifyingProperty(ref _date, value); } }
    	private Nullable<double> _formulavalue;
        public Nullable<double> FormulaValue { get { return _formulavalue; } set { SetNotifyingProperty(ref _formulavalue, value); } }
    	private Nullable<int> _formulavaluetype;
        public Nullable<int> FormulaValueType { get { return _formulavaluetype; } set { SetNotifyingProperty(ref _formulavaluetype, value); } }
    
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    }
}
