//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGeneral : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private Nullable<int> _accountid;
        public Nullable<int> AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private string _accountname;
        public string AccountName { get { return _accountname; } set { SetNotifyingProperty(ref _accountname, value); } }
    	private Nullable<int> _accounttype;
        public Nullable<int> AccountType { get { return _accounttype; } set { SetNotifyingProperty(ref _accounttype, value); } }
    }
}
