//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualGoodInStock : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private Nullable<int> _stockid;
        public Nullable<int> StockID { get { return _stockid; } set { SetNotifyingProperty(ref _stockid, value); } }
    	private Nullable<int> _goodid;
        public Nullable<int> GoodID { get { return _goodid; } set { SetNotifyingProperty(ref _goodid, value); } }
    	private Nullable<int> _parentid;
        public Nullable<int> ParentID { get { return _parentid; } set { SetNotifyingProperty(ref _parentid, value); } }
    	private Nullable<System.DateTime> _datein;
        public Nullable<System.DateTime> DateIn { get { return _datein; } set { SetNotifyingProperty(ref _datein, value); } }
    	private Nullable<System.DateTime> _updateddate;
        public Nullable<System.DateTime> UpdatedDate { get { return _updateddate; } set { SetNotifyingProperty(ref _updateddate, value); } }
    	private Nullable<int> _uomid;
        public Nullable<int> UOMID { get { return _uomid; } set { SetNotifyingProperty(ref _uomid, value); } }
    	private Nullable<int> _inputquantity;
        public Nullable<int> InputQuantity { get { return _inputquantity; } set { SetNotifyingProperty(ref _inputquantity, value); } }
    	private Nullable<int> _remainquantity;
        public Nullable<int> RemainQuantity { get { return _remainquantity; } set { SetNotifyingProperty(ref _remainquantity, value); } }
    	private Nullable<int> _outputquantity;
        public Nullable<int> OutputQuantity { get { return _outputquantity; } set { SetNotifyingProperty(ref _outputquantity, value); } }
    	private Nullable<double> _inputprice;
        public Nullable<double> InputPrice { get { return _inputprice; } set { SetNotifyingProperty(ref _inputprice, value); } }
    	private Nullable<int> _companyid;
        public Nullable<int> CompanyID { get { return _companyid; } set { SetNotifyingProperty(ref _companyid, value); } }
    
    	private Good _good;
        public virtual Good Good { get { return _good; } set { SetNotifyingProperty(ref _good, value); } }
    	private Company _company;
        public virtual Company Company { get { return _company; } set { SetNotifyingProperty(ref _company, value); } }
    }
}
