//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocWOItemDetail : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _allocwoid;
        public int AllocWOID { get { return _allocwoid; } set { SetNotifyingProperty(ref _allocwoid, value); } }
    	private int _goodid;
        public int GoodID { get { return _goodid; } set { SetNotifyingProperty(ref _goodid, value); } }
    	private double _price;
        public double Price { get { return _price; } set { SetNotifyingProperty(ref _price, value); } }
    	private int _allocqty;
        public int AllocQty { get { return _allocqty; } set { SetNotifyingProperty(ref _allocqty, value); } }
    	private Nullable<int> _implementquantity;
        public Nullable<int> ImplementQuantity { get { return _implementquantity; } set { SetNotifyingProperty(ref _implementquantity, value); } }
    	private Nullable<int> _remainquantity;
        public Nullable<int> RemainQuantity { get { return _remainquantity; } set { SetNotifyingProperty(ref _remainquantity, value); } }
    	private Nullable<int> _balancequantity;
        public Nullable<int> BalanceQuantity { get { return _balancequantity; } set { SetNotifyingProperty(ref _balancequantity, value); } }
    	private Nullable<int> _uomid;
        public Nullable<int> UOMID { get { return _uomid; } set { SetNotifyingProperty(ref _uomid, value); } }
    
    	private AllocWO _allocwo;
        public virtual AllocWO AllocWO { get { return _allocwo; } set { SetNotifyingProperty(ref _allocwo, value); } }
    	private Good _good;
        public virtual Good Good { get { return _good; } set { SetNotifyingProperty(ref _good, value); } }
    	private UOM _uom;
        public virtual UOM UOM { get { return _uom; } set { SetNotifyingProperty(ref _uom, value); } }
    }
}
