//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocWO : Entity
    {
        public AllocWO()
        {
            this.AllocWOItemDetails = new HashSet<AllocWOItemDetail>();
            this.ProductionMonitors = new HashSet<ProductionMonitor>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private int _workorderid;
        public int WorkOrderID { get { return _workorderid; } set { SetNotifyingProperty(ref _workorderid, value); } }
    	private Nullable<int> _workcenterid;
        public Nullable<int> WorkCenterID { get { return _workcenterid; } set { SetNotifyingProperty(ref _workcenterid, value); } }
    	private int _tostockid;
        public int ToStockID { get { return _tostockid; } set { SetNotifyingProperty(ref _tostockid, value); } }
    	private int _goodid;
        public int GoodID { get { return _goodid; } set { SetNotifyingProperty(ref _goodid, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private int _status;
        public int Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private Nullable<int> _stockoutcardid;
        public Nullable<int> StockOutCardID { get { return _stockoutcardid; } set { SetNotifyingProperty(ref _stockoutcardid, value); } }
    
    	private Good _good;
        public virtual Good Good { get { return _good; } set { SetNotifyingProperty(ref _good, value); } }
    	private StockOutCard _stockoutcard;
        public virtual StockOutCard StockOutCard { get { return _stockoutcard; } set { SetNotifyingProperty(ref _stockoutcard, value); } }
    	private Stock _stock;
        public virtual Stock Stock { get { return _stock; } set { SetNotifyingProperty(ref _stock, value); } }
    	private WorkCenter _workcenter;
        public virtual WorkCenter WorkCenter { get { return _workcenter; } set { SetNotifyingProperty(ref _workcenter, value); } }
    	private WorkOrder _workorder;
        public virtual WorkOrder WorkOrder { get { return _workorder; } set { SetNotifyingProperty(ref _workorder, value); } }
    	private ICollection<AllocWOItemDetail> _allocwoitemdetails;
        public virtual ICollection<AllocWOItemDetail> AllocWOItemDetails { get { return _allocwoitemdetails; } set { SetNotifyingProperty(ref _allocwoitemdetails, value); } }
    	private ICollection<ProductionMonitor> _productionmonitors;
        public virtual ICollection<ProductionMonitor> ProductionMonitors { get { return _productionmonitors; } set { SetNotifyingProperty(ref _productionmonitors, value); } }
    }
}
