//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount : Entity
    {
        public BankAccount()
        {
            this.BankStatements = new HashSet<BankStatement>();
            this.BankAccountBills = new HashSet<BankAccountBill>();
            this.AccountTrans = new HashSet<AccountTran>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _companyid;
        public int CompanyID { get { return _companyid; } set { SetNotifyingProperty(ref _companyid, value); } }
    	private string _bankname;
        public string BankName { get { return _bankname; } set { SetNotifyingProperty(ref _bankname, value); } }
    	private string _accoutname;
        public string AccoutName { get { return _accoutname; } set { SetNotifyingProperty(ref _accoutname, value); } }
    	private string _accoutnum;
        public string AccoutNum { get { return _accoutnum; } set { SetNotifyingProperty(ref _accoutnum, value); } }
    	private int _currencyid;
        public int CurrencyID { get { return _currencyid; } set { SetNotifyingProperty(ref _currencyid, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private Nullable<int> _showondashboard;
        public Nullable<int> ShowOnDashboard { get { return _showondashboard; } set { SetNotifyingProperty(ref _showondashboard, value); } }
    
    	private Company _company;
        public virtual Company Company { get { return _company; } set { SetNotifyingProperty(ref _company, value); } }
    	private ICollection<BankStatement> _bankstatements;
        public virtual ICollection<BankStatement> BankStatements { get { return _bankstatements; } set { SetNotifyingProperty(ref _bankstatements, value); } }
    	private ICollection<BankAccountBill> _bankaccountbills;
        public virtual ICollection<BankAccountBill> BankAccountBills { get { return _bankaccountbills; } set { SetNotifyingProperty(ref _bankaccountbills, value); } }
    	private Currency _currency;
        public virtual Currency Currency { get { return _currency; } set { SetNotifyingProperty(ref _currency, value); } }
    	private ICollection<AccountTran> _accounttrans;
        public virtual ICollection<AccountTran> AccountTrans { get { return _accounttrans; } set { SetNotifyingProperty(ref _accounttrans, value); } }
    }
}
