//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountDetail : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _bankaccountbillid;
        public int BankAccountBillID { get { return _bankaccountbillid; } set { SetNotifyingProperty(ref _bankaccountbillid, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<int> _relatedaccountid;
        public Nullable<int> RelatedAccountID { get { return _relatedaccountid; } set { SetNotifyingProperty(ref _relatedaccountid, value); } }
    	private int _quantity;
        public int Quantity { get { return _quantity; } set { SetNotifyingProperty(ref _quantity, value); } }
    	private double _unitprice;
        public double UnitPrice { get { return _unitprice; } set { SetNotifyingProperty(ref _unitprice, value); } }
    	private Nullable<int> _taxrateid;
        public Nullable<int> TaxRateID { get { return _taxrateid; } set { SetNotifyingProperty(ref _taxrateid, value); } }
    	private double _amount;
        public double Amount { get { return _amount; } set { SetNotifyingProperty(ref _amount, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    
    	private TaxRate _taxrate;
        public virtual TaxRate TaxRate { get { return _taxrate; } set { SetNotifyingProperty(ref _taxrate, value); } }
    	private BankAccountBill _bankaccountbill;
        public virtual BankAccountBill BankAccountBill { get { return _bankaccountbill; } set { SetNotifyingProperty(ref _bankaccountbill, value); } }
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    }
}
