//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankStatementDetail : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _bankstatementid;
        public int BankStatementID { get { return _bankstatementid; } set { SetNotifyingProperty(ref _bankstatementid, value); } }
    	private Nullable<System.DateTime> _date;
        public Nullable<System.DateTime> Date { get { return _date; } set { SetNotifyingProperty(ref _date, value); } }
    	private Nullable<int> _type;
        public Nullable<int> Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    	private string _payee;
        public string Payee { get { return _payee; } set { SetNotifyingProperty(ref _payee, value); } }
    	private string _particulars;
        public string Particulars { get { return _particulars; } set { SetNotifyingProperty(ref _particulars, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _reference;
        public string Reference { get { return _reference; } set { SetNotifyingProperty(ref _reference, value); } }
    	private string _analysiscode;
        public string AnalysisCode { get { return _analysiscode; } set { SetNotifyingProperty(ref _analysiscode, value); } }
    	private Nullable<double> _received;
        public Nullable<double> Received { get { return _received; } set { SetNotifyingProperty(ref _received, value); } }
    	private Nullable<double> _spent;
        public Nullable<double> Spent { get { return _spent; } set { SetNotifyingProperty(ref _spent, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    
    	private BankStatement _bankstatement;
        public virtual BankStatement BankStatement { get { return _bankstatement; } set { SetNotifyingProperty(ref _bankstatement, value); } }
    }
}
