//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountBill : Entity
    {
        public BankAccountBill()
        {
            this.BankAccountDetails = new HashSet<BankAccountDetail>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _bankaccountid;
        public int BankAccountID { get { return _bankaccountid; } set { SetNotifyingProperty(ref _bankaccountid, value); } }
    	private int _type;
        public int Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    	private string _contactname;
        public string ContactName { get { return _contactname; } set { SetNotifyingProperty(ref _contactname, value); } }
    	private System.DateTime _createddate;
        public System.DateTime CreatedDate { get { return _createddate; } set { SetNotifyingProperty(ref _createddate, value); } }
    	private string _reference;
        public string Reference { get { return _reference; } set { SetNotifyingProperty(ref _reference, value); } }
    	private int _amountare;
        public int AmountAre { get { return _amountare; } set { SetNotifyingProperty(ref _amountare, value); } }
    	private double _subtotal;
        public double Subtotal { get { return _subtotal; } set { SetNotifyingProperty(ref _subtotal, value); } }
    	private double _tax;
        public double Tax { get { return _tax; } set { SetNotifyingProperty(ref _tax, value); } }
    	private double _total;
        public double Total { get { return _total; } set { SetNotifyingProperty(ref _total, value); } }
    	private double _status;
        public double Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    
    	private BankAccount _bankaccount;
        public virtual BankAccount BankAccount { get { return _bankaccount; } set { SetNotifyingProperty(ref _bankaccount, value); } }
    	private ICollection<BankAccountDetail> _bankaccountdetails;
        public virtual ICollection<BankAccountDetail> BankAccountDetails { get { return _bankaccountdetails; } set { SetNotifyingProperty(ref _bankaccountdetails, value); } }
    }
}
