//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company : Entity
    {
        public Company()
        {
            this.BankAccounts = new HashSet<BankAccount>();
            this.Companies1 = new HashSet<Company>();
            this.SaleInvoices = new HashSet<SaleInvoice>();
            this.PayRuns = new HashSet<PayRun>();
            this.Purchases = new HashSet<Purchase>();
            this.StockOutCards = new HashSet<StockOutCard>();
            this.Users = new HashSet<User>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.Journals = new HashSet<Journal>();
            this.Employees = new HashSet<Employee>();
            this.AccountTrans = new HashSet<AccountTran>();
            this.StockInCards = new HashSet<StockInCard>();
            this.ActualGoodInStocks = new HashSet<ActualGoodInStock>();
            this.ProductionMonitors = new HashSet<ProductionMonitor>();
            this.WorkCenters = new HashSet<WorkCenter>();
            this.StockMovements = new HashSet<StockMovement>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _displayname;
        public string DisplayName { get { return _displayname; } set { SetNotifyingProperty(ref _displayname, value); } }
    	private string _tradingname;
        public string TradingName { get { return _tradingname; } set { SetNotifyingProperty(ref _tradingname, value); } }
    	private string _logo;
        public string Logo { get { return _logo; } set { SetNotifyingProperty(ref _logo, value); } }
    	private string _business;
        public string Business { get { return _business; } set { SetNotifyingProperty(ref _business, value); } }
    	private string _orgatype;
        public string OrgaType { get { return _orgatype; } set { SetNotifyingProperty(ref _orgatype, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private string _postattention;
        public string PostAttention { get { return _postattention; } set { SetNotifyingProperty(ref _postattention, value); } }
    	private string _postaddress;
        public string PostAddress { get { return _postaddress; } set { SetNotifyingProperty(ref _postaddress, value); } }
    	private string _postcity;
        public string PostCity { get { return _postcity; } set { SetNotifyingProperty(ref _postcity, value); } }
    	private string _poststate;
        public string PostState { get { return _poststate; } set { SetNotifyingProperty(ref _poststate, value); } }
    	private string _postzipcode;
        public string PostZipCode { get { return _postzipcode; } set { SetNotifyingProperty(ref _postzipcode, value); } }
    	private string _postcountry;
        public string PostCountry { get { return _postcountry; } set { SetNotifyingProperty(ref _postcountry, value); } }
    	private string _physattention;
        public string PhysAttention { get { return _physattention; } set { SetNotifyingProperty(ref _physattention, value); } }
    	private string _physaddress;
        public string PhysAddress { get { return _physaddress; } set { SetNotifyingProperty(ref _physaddress, value); } }
    	private string _physcity;
        public string PhysCity { get { return _physcity; } set { SetNotifyingProperty(ref _physcity, value); } }
    	private string _physstate;
        public string PhysState { get { return _physstate; } set { SetNotifyingProperty(ref _physstate, value); } }
    	private string _physzipcode;
        public string PhysZipCode { get { return _physzipcode; } set { SetNotifyingProperty(ref _physzipcode, value); } }
    	private string _physcountry;
        public string PhysCountry { get { return _physcountry; } set { SetNotifyingProperty(ref _physcountry, value); } }
    	private string _tel_country;
        public string Tel_Country { get { return _tel_country; } set { SetNotifyingProperty(ref _tel_country, value); } }
    	private string _tel_area;
        public string Tel_Area { get { return _tel_area; } set { SetNotifyingProperty(ref _tel_area, value); } }
    	private string _tel_num;
        public string Tel_Num { get { return _tel_num; } set { SetNotifyingProperty(ref _tel_num, value); } }
    	private string _email;
        public string Email { get { return _email; } set { SetNotifyingProperty(ref _email, value); } }
    	private string _website;
        public string Website { get { return _website; } set { SetNotifyingProperty(ref _website, value); } }
    	private Nullable<int> _parentid;
        public Nullable<int> ParentID { get { return _parentid; } set { SetNotifyingProperty(ref _parentid, value); } }
    
    	private ICollection<BankAccount> _bankaccounts;
        public virtual ICollection<BankAccount> BankAccounts { get { return _bankaccounts; } set { SetNotifyingProperty(ref _bankaccounts, value); } }
    	private ICollection<Company> _companies1;
        public virtual ICollection<Company> Companies1 { get { return _companies1; } set { SetNotifyingProperty(ref _companies1, value); } }
    	private Company _company1;
        public virtual Company Company1 { get { return _company1; } set { SetNotifyingProperty(ref _company1, value); } }
    	private ICollection<SaleInvoice> _saleinvoices;
        public virtual ICollection<SaleInvoice> SaleInvoices { get { return _saleinvoices; } set { SetNotifyingProperty(ref _saleinvoices, value); } }
    	private ICollection<PayRun> _payruns;
        public virtual ICollection<PayRun> PayRuns { get { return _payruns; } set { SetNotifyingProperty(ref _payruns, value); } }
    	private ICollection<Purchase> _purchases;
        public virtual ICollection<Purchase> Purchases { get { return _purchases; } set { SetNotifyingProperty(ref _purchases, value); } }
    	private ICollection<StockOutCard> _stockoutcards;
        public virtual ICollection<StockOutCard> StockOutCards { get { return _stockoutcards; } set { SetNotifyingProperty(ref _stockoutcards, value); } }
    	private ICollection<User> _users;
        public virtual ICollection<User> Users { get { return _users; } set { SetNotifyingProperty(ref _users, value); } }
    	private ICollection<WorkOrder> _workorders;
        public virtual ICollection<WorkOrder> WorkOrders { get { return _workorders; } set { SetNotifyingProperty(ref _workorders, value); } }
    	private ICollection<Journal> _journals;
        public virtual ICollection<Journal> Journals { get { return _journals; } set { SetNotifyingProperty(ref _journals, value); } }
    	private ICollection<Employee> _employees;
        public virtual ICollection<Employee> Employees { get { return _employees; } set { SetNotifyingProperty(ref _employees, value); } }
    	private ICollection<AccountTran> _accounttrans;
        public virtual ICollection<AccountTran> AccountTrans { get { return _accounttrans; } set { SetNotifyingProperty(ref _accounttrans, value); } }
    	private ICollection<StockInCard> _stockincards;
        public virtual ICollection<StockInCard> StockInCards { get { return _stockincards; } set { SetNotifyingProperty(ref _stockincards, value); } }
    	private ICollection<ActualGoodInStock> _actualgoodinstocks;
        public virtual ICollection<ActualGoodInStock> ActualGoodInStocks { get { return _actualgoodinstocks; } set { SetNotifyingProperty(ref _actualgoodinstocks, value); } }
    	private ICollection<ProductionMonitor> _productionmonitors;
        public virtual ICollection<ProductionMonitor> ProductionMonitors { get { return _productionmonitors; } set { SetNotifyingProperty(ref _productionmonitors, value); } }
    	private ICollection<WorkCenter> _workcenters;
        public virtual ICollection<WorkCenter> WorkCenters { get { return _workcenters; } set { SetNotifyingProperty(ref _workcenters, value); } }
    	private ICollection<StockMovement> _stockmovements;
        public virtual ICollection<StockMovement> StockMovements { get { return _stockmovements; } set { SetNotifyingProperty(ref _stockmovements, value); } }
    }
}
