//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control : Entity
    {
        public Control()
        {
            this.ControlInRoles = new HashSet<ControlInRole>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _functionid;
        public int FunctionID { get { return _functionid; } set { SetNotifyingProperty(ref _functionid, value); } }
    	private string _controlid;
        public string ControlID { get { return _controlid; } set { SetNotifyingProperty(ref _controlid, value); } }
    	private string _controlname;
        public string ControlName { get { return _controlname; } set { SetNotifyingProperty(ref _controlname, value); } }
    
    	private ICollection<ControlInRole> _controlinroles;
        public virtual ICollection<ControlInRole> ControlInRoles { get { return _controlinroles; } set { SetNotifyingProperty(ref _controlinroles, value); } }
    	private Function _function;
        public virtual Function Function { get { return _function; } set { SetNotifyingProperty(ref _function, value); } }
    }
}
