//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact : Entity
    {
        public Contact()
        {
            this.Purchases = new HashSet<Purchase>();
            this.SaleInvoices = new HashSet<SaleInvoice>();
            this.ExpenseClaims = new HashSet<ExpenseClaim>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _contactname;
        public string ContactName { get { return _contactname; } set { SetNotifyingProperty(ref _contactname, value); } }
    	private string _firstname;
        public string FirstName { get { return _firstname; } set { SetNotifyingProperty(ref _firstname, value); } }
    	private string _lastname;
        public string LastName { get { return _lastname; } set { SetNotifyingProperty(ref _lastname, value); } }
    	private int _type;
        public int Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    	private string _email;
        public string Email { get { return _email; } set { SetNotifyingProperty(ref _email, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private string _postattention;
        public string PostAttention { get { return _postattention; } set { SetNotifyingProperty(ref _postattention, value); } }
    	private string _postaddress;
        public string PostAddress { get { return _postaddress; } set { SetNotifyingProperty(ref _postaddress, value); } }
    	private string _postcity;
        public string PostCity { get { return _postcity; } set { SetNotifyingProperty(ref _postcity, value); } }
    	private string _poststate;
        public string PostState { get { return _poststate; } set { SetNotifyingProperty(ref _poststate, value); } }
    	private string _postzipcode;
        public string PostZipCode { get { return _postzipcode; } set { SetNotifyingProperty(ref _postzipcode, value); } }
    	private string _postcountry;
        public string PostCountry { get { return _postcountry; } set { SetNotifyingProperty(ref _postcountry, value); } }
    	private string _physattention;
        public string PhysAttention { get { return _physattention; } set { SetNotifyingProperty(ref _physattention, value); } }
    	private string _physaddress;
        public string PhysAddress { get { return _physaddress; } set { SetNotifyingProperty(ref _physaddress, value); } }
    	private string _physcity;
        public string PhysCity { get { return _physcity; } set { SetNotifyingProperty(ref _physcity, value); } }
    	private string _physstate;
        public string PhysState { get { return _physstate; } set { SetNotifyingProperty(ref _physstate, value); } }
    	private string _physzipcode;
        public string PhysZipCode { get { return _physzipcode; } set { SetNotifyingProperty(ref _physzipcode, value); } }
    	private string _physcountry;
        public string PhysCountry { get { return _physcountry; } set { SetNotifyingProperty(ref _physcountry, value); } }
    	private string _countryname;
        public string CountryName { get { return _countryname; } set { SetNotifyingProperty(ref _countryname, value); } }
    	private string _tel_country;
        public string Tel_Country { get { return _tel_country; } set { SetNotifyingProperty(ref _tel_country, value); } }
    	private string _tel_area;
        public string Tel_Area { get { return _tel_area; } set { SetNotifyingProperty(ref _tel_area, value); } }
    	private string _tel_num;
        public string Tel_Num { get { return _tel_num; } set { SetNotifyingProperty(ref _tel_num, value); } }
    	private string _fax_country;
        public string Fax_Country { get { return _fax_country; } set { SetNotifyingProperty(ref _fax_country, value); } }
    	private string _fax_area;
        public string Fax_Area { get { return _fax_area; } set { SetNotifyingProperty(ref _fax_area, value); } }
    	private string _fax_num;
        public string Fax_Num { get { return _fax_num; } set { SetNotifyingProperty(ref _fax_num, value); } }
    	private string _mobi_country;
        public string Mobi_Country { get { return _mobi_country; } set { SetNotifyingProperty(ref _mobi_country, value); } }
    	private string _mobi_area;
        public string Mobi_Area { get { return _mobi_area; } set { SetNotifyingProperty(ref _mobi_area, value); } }
    	private string _mobi_num;
        public string Mobi_Num { get { return _mobi_num; } set { SetNotifyingProperty(ref _mobi_num, value); } }
    	private string _direct_country;
        public string Direct_Country { get { return _direct_country; } set { SetNotifyingProperty(ref _direct_country, value); } }
    	private string _direct_area;
        public string Direct_Area { get { return _direct_area; } set { SetNotifyingProperty(ref _direct_area, value); } }
    	private string _direct_num;
        public string Direct_Num { get { return _direct_num; } set { SetNotifyingProperty(ref _direct_num, value); } }
    	private string _skypename;
        public string SkypeName { get { return _skypename; } set { SetNotifyingProperty(ref _skypename, value); } }
    	private string _website;
        public string Website { get { return _website; } set { SetNotifyingProperty(ref _website, value); } }
    	private string _taxnumber;
        public string TaxNumber { get { return _taxnumber; } set { SetNotifyingProperty(ref _taxnumber, value); } }
    	private Nullable<int> _saletaxid;
        public Nullable<int> SaleTaxID { get { return _saletaxid; } set { SetNotifyingProperty(ref _saletaxid, value); } }
    	private Nullable<int> _purchasestaxid;
        public Nullable<int> PurchasesTaxID { get { return _purchasestaxid; } set { SetNotifyingProperty(ref _purchasestaxid, value); } }
    	private Nullable<double> _discount;
        public Nullable<double> Discount { get { return _discount; } set { SetNotifyingProperty(ref _discount, value); } }
    	private Nullable<int> _currencyid;
        public Nullable<int> CurrencyID { get { return _currencyid; } set { SetNotifyingProperty(ref _currencyid, value); } }
    	private string _bankaccoutnum;
        public string BankAccoutNum { get { return _bankaccoutnum; } set { SetNotifyingProperty(ref _bankaccoutnum, value); } }
    	private string _bankaccountname;
        public string BankAccountName { get { return _bankaccountname; } set { SetNotifyingProperty(ref _bankaccountname, value); } }
    	private string _bankaccountdetail;
        public string BankAccountDetail { get { return _bankaccountdetail; } set { SetNotifyingProperty(ref _bankaccountdetail, value); } }
    
    	private Currency _currency;
        public virtual Currency Currency { get { return _currency; } set { SetNotifyingProperty(ref _currency, value); } }
    	private TaxRate _taxrate;
        public virtual TaxRate TaxRate { get { return _taxrate; } set { SetNotifyingProperty(ref _taxrate, value); } }
    	private TaxRate _taxrate1;
        public virtual TaxRate TaxRate1 { get { return _taxrate1; } set { SetNotifyingProperty(ref _taxrate1, value); } }
    	private ICollection<Purchase> _purchases;
        public virtual ICollection<Purchase> Purchases { get { return _purchases; } set { SetNotifyingProperty(ref _purchases, value); } }
    	private ICollection<SaleInvoice> _saleinvoices;
        public virtual ICollection<SaleInvoice> SaleInvoices { get { return _saleinvoices; } set { SetNotifyingProperty(ref _saleinvoices, value); } }
    	private ICollection<ExpenseClaim> _expenseclaims;
        public virtual ICollection<ExpenseClaim> ExpenseClaims { get { return _expenseclaims; } set { SetNotifyingProperty(ref _expenseclaims, value); } }
    }
}
