//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlInRole : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private Nullable<int> _roleid;
        public Nullable<int> RoleID { get { return _roleid; } set { SetNotifyingProperty(ref _roleid, value); } }
    	private Nullable<int> _controlid;
        public Nullable<int> ControlID { get { return _controlid; } set { SetNotifyingProperty(ref _controlid, value); } }
    	private Nullable<int> _viewtype;
        public Nullable<int> ViewType { get { return _viewtype; } set { SetNotifyingProperty(ref _viewtype, value); } }
    
    	private Control _control;
        public virtual Control Control { get { return _control; } set { SetNotifyingProperty(ref _control, value); } }
    	private Role _role;
        public virtual Role Role { get { return _role; } set { SetNotifyingProperty(ref _role, value); } }
    }
}
