//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency : Entity
    {
        public Currency()
        {
            this.Purchases = new HashSet<Purchase>();
            this.SaleInvoices = new HashSet<SaleInvoice>();
            this.Contacts = new HashSet<Contact>();
            this.BankAccounts = new HashSet<BankAccount>();
            this.Payments = new HashSet<Payment>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private Nullable<double> _foreignexchange;
        public Nullable<double> ForeignExchange { get { return _foreignexchange; } set { SetNotifyingProperty(ref _foreignexchange, value); } }
    	private Nullable<double> _homeexchange;
        public Nullable<double> HomeExchange { get { return _homeexchange; } set { SetNotifyingProperty(ref _homeexchange, value); } }
    	private int _status;
        public int Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private string _descripttion;
        public string Descripttion { get { return _descripttion; } set { SetNotifyingProperty(ref _descripttion, value); } }
    
    	private ICollection<Purchase> _purchases;
        public virtual ICollection<Purchase> Purchases { get { return _purchases; } set { SetNotifyingProperty(ref _purchases, value); } }
    	private ICollection<SaleInvoice> _saleinvoices;
        public virtual ICollection<SaleInvoice> SaleInvoices { get { return _saleinvoices; } set { SetNotifyingProperty(ref _saleinvoices, value); } }
    	private ICollection<Contact> _contacts;
        public virtual ICollection<Contact> Contacts { get { return _contacts; } set { SetNotifyingProperty(ref _contacts, value); } }
    	private ICollection<BankAccount> _bankaccounts;
        public virtual ICollection<BankAccount> BankAccounts { get { return _bankaccounts; } set { SetNotifyingProperty(ref _bankaccounts, value); } }
    	private ICollection<Payment> _payments;
        public virtual ICollection<Payment> Payments { get { return _payments; } set { SetNotifyingProperty(ref _payments, value); } }
    }
}
