//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DueDateType : Entity
    {
        public DueDateType()
        {
            this.SaleInvoiceSettings = new HashSet<SaleInvoiceSetting>();
            this.SaleInvoiceSettings1 = new HashSet<SaleInvoiceSetting>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    
    	private ICollection<SaleInvoiceSetting> _saleinvoicesettings;
        public virtual ICollection<SaleInvoiceSetting> SaleInvoiceSettings { get { return _saleinvoicesettings; } set { SetNotifyingProperty(ref _saleinvoicesettings, value); } }
    	private ICollection<SaleInvoiceSetting> _saleinvoicesettings1;
        public virtual ICollection<SaleInvoiceSetting> SaleInvoiceSettings1 { get { return _saleinvoicesettings1; } set { SetNotifyingProperty(ref _saleinvoicesettings1, value); } }
    }
}
