//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : Entity
    {
        public Employee()
        {
            this.PayRunEmployees = new HashSet<PayRunEmployee>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _firstname;
        public string FirstName { get { return _firstname; } set { SetNotifyingProperty(ref _firstname, value); } }
    	private string _lastname;
        public string LastName { get { return _lastname; } set { SetNotifyingProperty(ref _lastname, value); } }
    	private string _email;
        public string Email { get { return _email; } set { SetNotifyingProperty(ref _email, value); } }
    	private string _password;
        public string Password { get { return _password; } set { SetNotifyingProperty(ref _password, value); } }
    	private int _companyid;
        public int CompanyID { get { return _companyid; } set { SetNotifyingProperty(ref _companyid, value); } }
    	private string _postattention;
        public string PostAttention { get { return _postattention; } set { SetNotifyingProperty(ref _postattention, value); } }
    	private string _postaddress;
        public string PostAddress { get { return _postaddress; } set { SetNotifyingProperty(ref _postaddress, value); } }
    	private string _postcity;
        public string PostCity { get { return _postcity; } set { SetNotifyingProperty(ref _postcity, value); } }
    	private string _poststate;
        public string PostState { get { return _poststate; } set { SetNotifyingProperty(ref _poststate, value); } }
    	private string _postzipcode;
        public string PostZipCode { get { return _postzipcode; } set { SetNotifyingProperty(ref _postzipcode, value); } }
    	private string _postcountry;
        public string PostCountry { get { return _postcountry; } set { SetNotifyingProperty(ref _postcountry, value); } }
    	private string _physattention;
        public string PhysAttention { get { return _physattention; } set { SetNotifyingProperty(ref _physattention, value); } }
    	private string _physaddress;
        public string PhysAddress { get { return _physaddress; } set { SetNotifyingProperty(ref _physaddress, value); } }
    	private string _physcity;
        public string PhysCity { get { return _physcity; } set { SetNotifyingProperty(ref _physcity, value); } }
    	private string _physstate;
        public string PhysState { get { return _physstate; } set { SetNotifyingProperty(ref _physstate, value); } }
    	private string _physzipcode;
        public string PhysZipCode { get { return _physzipcode; } set { SetNotifyingProperty(ref _physzipcode, value); } }
    	private string _physcountry;
        public string PhysCountry { get { return _physcountry; } set { SetNotifyingProperty(ref _physcountry, value); } }
    	private string _countryname;
        public string CountryName { get { return _countryname; } set { SetNotifyingProperty(ref _countryname, value); } }
    	private string _tel_country;
        public string Tel_Country { get { return _tel_country; } set { SetNotifyingProperty(ref _tel_country, value); } }
    	private string _tel_area;
        public string Tel_Area { get { return _tel_area; } set { SetNotifyingProperty(ref _tel_area, value); } }
    	private string _tel_num;
        public string Tel_Num { get { return _tel_num; } set { SetNotifyingProperty(ref _tel_num, value); } }
    	private string _fax_country;
        public string Fax_Country { get { return _fax_country; } set { SetNotifyingProperty(ref _fax_country, value); } }
    	private string _fax_area;
        public string Fax_Area { get { return _fax_area; } set { SetNotifyingProperty(ref _fax_area, value); } }
    	private string _fax_num;
        public string Fax_Num { get { return _fax_num; } set { SetNotifyingProperty(ref _fax_num, value); } }
    	private string _mobi_country;
        public string Mobi_Country { get { return _mobi_country; } set { SetNotifyingProperty(ref _mobi_country, value); } }
    	private string _mobi_area;
        public string Mobi_Area { get { return _mobi_area; } set { SetNotifyingProperty(ref _mobi_area, value); } }
    	private string _mobi_num;
        public string Mobi_Num { get { return _mobi_num; } set { SetNotifyingProperty(ref _mobi_num, value); } }
    	private string _direct_country;
        public string Direct_Country { get { return _direct_country; } set { SetNotifyingProperty(ref _direct_country, value); } }
    	private string _direct_area;
        public string Direct_Area { get { return _direct_area; } set { SetNotifyingProperty(ref _direct_area, value); } }
    	private string _direct_num;
        public string Direct_Num { get { return _direct_num; } set { SetNotifyingProperty(ref _direct_num, value); } }
    	private string _facebook;
        public string Facebook { get { return _facebook; } set { SetNotifyingProperty(ref _facebook, value); } }
    	private string _twitter;
        public string Twitter { get { return _twitter; } set { SetNotifyingProperty(ref _twitter, value); } }
    	private string _linkedin;
        public string LinkedIn { get { return _linkedin; } set { SetNotifyingProperty(ref _linkedin, value); } }
    	private string _google;
        public string Google { get { return _google; } set { SetNotifyingProperty(ref _google, value); } }
    	private string _taxnumber;
        public string TaxNumber { get { return _taxnumber; } set { SetNotifyingProperty(ref _taxnumber, value); } }
    	private string _ordinaryrate;
        public string OrdinaryRate { get { return _ordinaryrate; } set { SetNotifyingProperty(ref _ordinaryrate, value); } }
    	private string _bankaccountnumber;
        public string BankAccountNumber { get { return _bankaccountnumber; } set { SetNotifyingProperty(ref _bankaccountnumber, value); } }
    	private string _bankaccountname;
        public string BankAccountName { get { return _bankaccountname; } set { SetNotifyingProperty(ref _bankaccountname, value); } }
    	private string _paymentdetails;
        public string PaymentDetails { get { return _paymentdetails; } set { SetNotifyingProperty(ref _paymentdetails, value); } }
    
    	private Company _company;
        public virtual Company Company { get { return _company; } set { SetNotifyingProperty(ref _company, value); } }
    	private ICollection<PayRunEmployee> _payrunemployees;
        public virtual ICollection<PayRunEmployee> PayRunEmployees { get { return _payrunemployees; } set { SetNotifyingProperty(ref _payrunemployees, value); } }
    }
}
