//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErpEntities : DbContext
    {
        public ErpEntities()
            : base("name=ErpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountBudgetTran> AccountBudgetTrans { get; set; }
        public DbSet<AccountGoodTran> AccountGoodTrans { get; set; }
        public DbSet<AccountTranDetail> AccountTranDetails { get; set; }
        public DbSet<AccountType> AccountTypes { get; set; }
        public DbSet<Budget> Budgets { get; set; }
        public DbSet<Business> Businesses { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<DueDateType> DueDateTypes { get; set; }
        public DbSet<FinancialSetting> FinancialSettings { get; set; }
        public DbSet<FixedAssetDetail> FixedAssetDetails { get; set; }
        public DbSet<MachineHistory> MachineHistories { get; set; }
        public DbSet<Machine> Machines { get; set; }
        public DbSet<Note> Notes { get; set; }
        public DbSet<ProcessMachine> ProcessMachines { get; set; }
        public DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public DbSet<SaleInvoiceDetail> SaleInvoiceDetails { get; set; }
        public DbSet<SaleInvoiceSetting> SaleInvoiceSettings { get; set; }
        public DbSet<StockInCardsDetail> StockInCardsDetails { get; set; }
        public DbSet<StockMovementDetail> StockMovementDetails { get; set; }
        public DbSet<StockOutCardsDetail> StockOutCardsDetails { get; set; }
        public DbSet<TaxRate> TaxRates { get; set; }
        public DbSet<UOM> UOMs { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WorkCenter> WorkCenters { get; set; }
        public DbSet<StockOutCard> StockOutCards { get; set; }
        public DbSet<Purchase> Purchases { get; set; }
        public DbSet<SaleInvoice> SaleInvoices { get; set; }
        public DbSet<ActualGoodInStock> ActualGoodInStocks { get; set; }
        public DbSet<SubGood> SubGoods { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<StockMovementTemp> StockMovementTemps { get; set; }
        public DbSet<AccountFeature> AccountFeatures { get; set; }
        public DbSet<BankStatementDetail> BankStatementDetails { get; set; }
        public DbSet<BankStatement> BankStatements { get; set; }
        public DbSet<AccountBalance> AccountBalances { get; set; }
        public DbSet<BankAccountDetail> BankAccountDetails { get; set; }
        public DbSet<UsersInRole> UsersInRoles { get; set; }
        public DbSet<BankAccount> BankAccounts { get; set; }
        public DbSet<Function> Functions { get; set; }
        public DbSet<RoleFunction> RoleFunctions { get; set; }
        public DbSet<SubFunction> SubFunctions { get; set; }
        public DbSet<AccountGeneral> AccountGenerals { get; set; }
        public DbSet<BankAccountBill> BankAccountBills { get; set; }
        public DbSet<AccountGroup> AccountGroups { get; set; }
        public DbSet<AccountInGroup> AccountInGroups { get; set; }
        public DbSet<RolePermission> RolePermissions { get; set; }
        public DbSet<GoodType> GoodTypes { get; set; }
        public DbSet<ProductionMonitor> ProductionMonitors { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<WorkOrderDetail> WorkOrderDetails { get; set; }
        public DbSet<WorkOrder> WorkOrders { get; set; }
        public DbSet<Repeating> Repeatings { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<BOM> BOMs { get; set; }
        public DbSet<BomDetail> BomDetails { get; set; }
        public DbSet<FixedAssetSetting> FixedAssetSettings { get; set; }
        public DbSet<PayItemType> PayItemTypes { get; set; }
        public DbSet<ExpenseClaim> ExpenseClaims { get; set; }
        public DbSet<PayRun> PayRuns { get; set; }
        public DbSet<FixedAsset> FixedAssets { get; set; }
        public DbSet<ExpenseClaimDetail> ExpenseClaimDetails { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Good> Goods { get; set; }
        public DbSet<PayRunEmployee> PayRunEmployees { get; set; }
        public DbSet<PaymentForPayItem> PaymentForPayItems { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<PayRunEmployeeDetail> PayRunEmployeeDetails { get; set; }
        public DbSet<JournalDetail> JournalDetails { get; set; }
        public DbSet<Journal> Journals { get; set; }
        public DbSet<PayItem> PayItems { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Feature> Features { get; set; }
        public DbSet<AccountTran> AccountTrans { get; set; }
        public DbSet<ControlInRole> ControlInRoles { get; set; }
        public DbSet<Control> Controls { get; set; }
        public DbSet<StockInCard> StockInCards { get; set; }
        public DbSet<Stock> Stocks { get; set; }
        public DbSet<Account> Accounts { get; set; }
        public DbSet<StockMovement> StockMovements { get; set; }
        public DbSet<AllocWO> AllocWOes { get; set; }
        public DbSet<AllocWOItemDetail> AllocWOItemDetails { get; set; }
    }
}
