//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseClaim : Entity
    {
        public ExpenseClaim()
        {
            this.ExpenseClaimDetails = new HashSet<ExpenseClaimDetail>();
            this.Payments = new HashSet<Payment>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _createduserid;
        public int CreatedUserID { get { return _createduserid; } set { SetNotifyingProperty(ref _createduserid, value); } }
    	private int _approvaluserid;
        public int ApprovalUserID { get { return _approvaluserid; } set { SetNotifyingProperty(ref _approvaluserid, value); } }
    	private System.DateTime _createddate;
        public System.DateTime CreatedDate { get { return _createddate; } set { SetNotifyingProperty(ref _createddate, value); } }
    	private string _reference;
        public string Reference { get { return _reference; } set { SetNotifyingProperty(ref _reference, value); } }
    	private double _totalmoney;
        public double TotalMoney { get { return _totalmoney; } set { SetNotifyingProperty(ref _totalmoney, value); } }
    	private int _includetax;
        public int IncludeTax { get { return _includetax; } set { SetNotifyingProperty(ref _includetax, value); } }
    	private int _status;
        public int Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private Nullable<int> _receiptfrom;
        public Nullable<int> ReceiptFrom { get { return _receiptfrom; } set { SetNotifyingProperty(ref _receiptfrom, value); } }
    	private System.DateTime _receiptdate;
        public System.DateTime ReceiptDate { get { return _receiptdate; } set { SetNotifyingProperty(ref _receiptdate, value); } }
    	private Nullable<double> _totaltax;
        public Nullable<double> TotalTax { get { return _totaltax; } set { SetNotifyingProperty(ref _totaltax, value); } }
    	private Nullable<System.DateTime> _duedate;
        public Nullable<System.DateTime> DueDate { get { return _duedate; } set { SetNotifyingProperty(ref _duedate, value); } }
    	private Nullable<System.DateTime> _submitdate;
        public Nullable<System.DateTime> SubmitDate { get { return _submitdate; } set { SetNotifyingProperty(ref _submitdate, value); } }
    	private Nullable<System.DateTime> _reportingdate;
        public Nullable<System.DateTime> ReportingDate { get { return _reportingdate; } set { SetNotifyingProperty(ref _reportingdate, value); } }
    	private Nullable<int> _amountare;
        public Nullable<int> AmountAre { get { return _amountare; } set { SetNotifyingProperty(ref _amountare, value); } }
    	private Nullable<double> _remainmoney;
        public Nullable<double> RemainMoney { get { return _remainmoney; } set { SetNotifyingProperty(ref _remainmoney, value); } }
    
    	private User _user;
        public virtual User User { get { return _user; } set { SetNotifyingProperty(ref _user, value); } }
    	private User _user1;
        public virtual User User1 { get { return _user1; } set { SetNotifyingProperty(ref _user1, value); } }
    	private ICollection<ExpenseClaimDetail> _expenseclaimdetails;
        public virtual ICollection<ExpenseClaimDetail> ExpenseClaimDetails { get { return _expenseclaimdetails; } set { SetNotifyingProperty(ref _expenseclaimdetails, value); } }
    	private Contact _contact;
        public virtual Contact Contact { get { return _contact; } set { SetNotifyingProperty(ref _contact, value); } }
    	private ICollection<Payment> _payments;
        public virtual ICollection<Payment> Payments { get { return _payments; } set { SetNotifyingProperty(ref _payments, value); } }
    }
}
