//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseClaimDetail : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _expenseclaimid;
        public int ExpenseClaimID { get { return _expenseclaimid; } set { SetNotifyingProperty(ref _expenseclaimid, value); } }
    	private Nullable<int> _quantity;
        public Nullable<int> Quantity { get { return _quantity; } set { SetNotifyingProperty(ref _quantity, value); } }
    	private Nullable<double> _price;
        public Nullable<double> Price { get { return _price; } set { SetNotifyingProperty(ref _price, value); } }
    	private Nullable<double> _totalmoney;
        public Nullable<double> TotalMoney { get { return _totalmoney; } set { SetNotifyingProperty(ref _totalmoney, value); } }
    	private Nullable<int> _accountid;
        public Nullable<int> AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private Nullable<int> _taxrateid;
        public Nullable<int> TaxRateID { get { return _taxrateid; } set { SetNotifyingProperty(ref _taxrateid, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    
    	private ExpenseClaim _expenseclaim;
        public virtual ExpenseClaim ExpenseClaim { get { return _expenseclaim; } set { SetNotifyingProperty(ref _expenseclaim, value); } }
    	private TaxRate _taxrate;
        public virtual TaxRate TaxRate { get { return _taxrate; } set { SetNotifyingProperty(ref _taxrate, value); } }
    	private TaxRate _taxrate1;
        public virtual TaxRate TaxRate1 { get { return _taxrate1; } set { SetNotifyingProperty(ref _taxrate1, value); } }
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    }
}
