//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedAsset : Entity
    {
        public FixedAsset()
        {
            this.FixedAssetDetails = new HashSet<FixedAssetDetail>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private Nullable<int> _accountid;
        public Nullable<int> AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private Nullable<System.DateTime> _purchasedate;
        public Nullable<System.DateTime> PurchaseDate { get { return _purchasedate; } set { SetNotifyingProperty(ref _purchasedate, value); } }
    	private Nullable<double> _purchaseprice;
        public Nullable<double> PurchasePrice { get { return _purchaseprice; } set { SetNotifyingProperty(ref _purchaseprice, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<double> _accumulateddepreciation;
        public Nullable<double> AccumulatedDepreciation { get { return _accumulateddepreciation; } set { SetNotifyingProperty(ref _accumulateddepreciation, value); } }
    	private string _assettype;
        public string AssetType { get { return _assettype; } set { SetNotifyingProperty(ref _assettype, value); } }
    	private Nullable<double> _depreciationrate;
        public Nullable<double> DepreciationRate { get { return _depreciationrate; } set { SetNotifyingProperty(ref _depreciationrate, value); } }
    	private Nullable<int> _depreciationmethod;
        public Nullable<int> DepreciationMethod { get { return _depreciationmethod; } set { SetNotifyingProperty(ref _depreciationmethod, value); } }
    	private Nullable<int> _depreciationaccountid;
        public Nullable<int> DepreciationAccountID { get { return _depreciationaccountid; } set { SetNotifyingProperty(ref _depreciationaccountid, value); } }
    	private Nullable<int> _accumulateddepreciationaccountid;
        public Nullable<int> AccumulatedDepreciationAccountID { get { return _accumulateddepreciationaccountid; } set { SetNotifyingProperty(ref _accumulateddepreciationaccountid, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private Nullable<System.DateTime> _createddate;
        public Nullable<System.DateTime> CreatedDate { get { return _createddate; } set { SetNotifyingProperty(ref _createddate, value); } }
    	private Nullable<int> _createduserid;
        public Nullable<int> CreatedUserID { get { return _createduserid; } set { SetNotifyingProperty(ref _createduserid, value); } }
    	private Nullable<int> _fixedassetsettingid;
        public Nullable<int> FixedAssetSettingID { get { return _fixedassetsettingid; } set { SetNotifyingProperty(ref _fixedassetsettingid, value); } }
    	private Nullable<System.DateTime> _approveddate;
        public Nullable<System.DateTime> ApprovedDate { get { return _approveddate; } set { SetNotifyingProperty(ref _approveddate, value); } }
    
    	private ICollection<FixedAssetDetail> _fixedassetdetails;
        public virtual ICollection<FixedAssetDetail> FixedAssetDetails { get { return _fixedassetdetails; } set { SetNotifyingProperty(ref _fixedassetdetails, value); } }
    	private FixedAssetSetting _fixedassetsetting;
        public virtual FixedAssetSetting FixedAssetSetting { get { return _fixedassetsetting; } set { SetNotifyingProperty(ref _fixedassetsetting, value); } }
    	private User _user;
        public virtual User User { get { return _user; } set { SetNotifyingProperty(ref _user, value); } }
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    	private Account _account1;
        public virtual Account Account1 { get { return _account1; } set { SetNotifyingProperty(ref _account1, value); } }
    	private Account _account2;
        public virtual Account Account2 { get { return _account2; } set { SetNotifyingProperty(ref _account2, value); } }
    }
}
