//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function : Entity
    {
        public Function()
        {
            this.SubFunctions = new HashSet<SubFunction>();
            this.Controls = new HashSet<Control>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<int> _featureid;
        public Nullable<int> FeatureID { get { return _featureid; } set { SetNotifyingProperty(ref _featureid, value); } }
    
    	private ICollection<SubFunction> _subfunctions;
        public virtual ICollection<SubFunction> SubFunctions { get { return _subfunctions; } set { SetNotifyingProperty(ref _subfunctions, value); } }
    	private Feature _feature;
        public virtual Feature Feature { get { return _feature; } set { SetNotifyingProperty(ref _feature, value); } }
    	private ICollection<Control> _controls;
        public virtual ICollection<Control> Controls { get { return _controls; } set { SetNotifyingProperty(ref _controls, value); } }
    }
}
