//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good : Entity
    {
        public Good()
        {
            this.ActualGoodInStocks = new HashSet<ActualGoodInStock>();
            this.BomDetails = new HashSet<BomDetail>();
            this.BomDetails1 = new HashSet<BomDetail>();
            this.BOMs = new HashSet<BOM>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.SaleInvoiceDetails = new HashSet<SaleInvoiceDetail>();
            this.StockInCardsDetails = new HashSet<StockInCardsDetail>();
            this.StockMovementDetails = new HashSet<StockMovementDetail>();
            this.StockOutCardsDetails = new HashSet<StockOutCardsDetail>();
            this.SubGoods = new HashSet<SubGood>();
            this.SubGoods1 = new HashSet<SubGood>();
            this.WorkOrderDetails = new HashSet<WorkOrderDetail>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.AllocWOes = new HashSet<AllocWO>();
            this.AllocWOItemDetails = new HashSet<AllocWOItemDetail>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private string _attachment;
        public string Attachment { get { return _attachment; } set { SetNotifyingProperty(ref _attachment, value); } }
    	private Nullable<int> _contactid;
        public Nullable<int> ContactID { get { return _contactid; } set { SetNotifyingProperty(ref _contactid, value); } }
    	private int _producttypeid;
        public int ProductTypeID { get { return _producttypeid; } set { SetNotifyingProperty(ref _producttypeid, value); } }
    	private int _uomid;
        public int UOMID { get { return _uomid; } set { SetNotifyingProperty(ref _uomid, value); } }
    	private Nullable<double> _inputprice;
        public Nullable<double> InputPrice { get { return _inputprice; } set { SetNotifyingProperty(ref _inputprice, value); } }
    	private Nullable<double> _outputprice;
        public Nullable<double> OutputPrice { get { return _outputprice; } set { SetNotifyingProperty(ref _outputprice, value); } }
    	private Nullable<double> _domesticprice;
        public Nullable<double> DomesticPrice { get { return _domesticprice; } set { SetNotifyingProperty(ref _domesticprice, value); } }
    	private Nullable<System.DateTime> _starteddate;
        public Nullable<System.DateTime> StartedDate { get { return _starteddate; } set { SetNotifyingProperty(ref _starteddate, value); } }
    	private Nullable<System.DateTime> _perioddate;
        public Nullable<System.DateTime> PeriodDate { get { return _perioddate; } set { SetNotifyingProperty(ref _perioddate, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<int> _saleaccountid;
        public Nullable<int> SaleAccountID { get { return _saleaccountid; } set { SetNotifyingProperty(ref _saleaccountid, value); } }
    	private Nullable<int> _saletaxrateid;
        public Nullable<int> SaleTaxRateID { get { return _saletaxrateid; } set { SetNotifyingProperty(ref _saletaxrateid, value); } }
    	private Nullable<int> _purchaseaccountid;
        public Nullable<int> PurchaseAccountID { get { return _purchaseaccountid; } set { SetNotifyingProperty(ref _purchaseaccountid, value); } }
    	private Nullable<int> _purchasetaxrateid;
        public Nullable<int> PurchaseTaxRateID { get { return _purchasetaxrateid; } set { SetNotifyingProperty(ref _purchasetaxrateid, value); } }
    	private Nullable<int> _active;
        public Nullable<int> Active { get { return _active; } set { SetNotifyingProperty(ref _active, value); } }
    	private Nullable<int> _lock;
        public Nullable<int> Lock { get { return _lock; } set { SetNotifyingProperty(ref _lock, value); } }
    	private Nullable<int> _categoryid;
        public Nullable<int> CategoryID { get { return _categoryid; } set { SetNotifyingProperty(ref _categoryid, value); } }
    
    	private ICollection<ActualGoodInStock> _actualgoodinstocks;
        public virtual ICollection<ActualGoodInStock> ActualGoodInStocks { get { return _actualgoodinstocks; } set { SetNotifyingProperty(ref _actualgoodinstocks, value); } }
    	private ICollection<BomDetail> _bomdetails;
        public virtual ICollection<BomDetail> BomDetails { get { return _bomdetails; } set { SetNotifyingProperty(ref _bomdetails, value); } }
    	private ICollection<BomDetail> _bomdetails1;
        public virtual ICollection<BomDetail> BomDetails1 { get { return _bomdetails1; } set { SetNotifyingProperty(ref _bomdetails1, value); } }
    	private ICollection<BOM> _boms;
        public virtual ICollection<BOM> BOMs { get { return _boms; } set { SetNotifyingProperty(ref _boms, value); } }
    	private Category _category;
        public virtual Category Category { get { return _category; } set { SetNotifyingProperty(ref _category, value); } }
    	private ProductType _producttype;
        public virtual ProductType ProductType { get { return _producttype; } set { SetNotifyingProperty(ref _producttype, value); } }
    	private TaxRate _taxrate;
        public virtual TaxRate TaxRate { get { return _taxrate; } set { SetNotifyingProperty(ref _taxrate, value); } }
    	private TaxRate _taxrate1;
        public virtual TaxRate TaxRate1 { get { return _taxrate1; } set { SetNotifyingProperty(ref _taxrate1, value); } }
    	private UOM _uom;
        public virtual UOM UOM { get { return _uom; } set { SetNotifyingProperty(ref _uom, value); } }
    	private ICollection<PurchaseDetail> _purchasedetails;
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get { return _purchasedetails; } set { SetNotifyingProperty(ref _purchasedetails, value); } }
    	private ICollection<SaleInvoiceDetail> _saleinvoicedetails;
        public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get { return _saleinvoicedetails; } set { SetNotifyingProperty(ref _saleinvoicedetails, value); } }
    	private ICollection<StockInCardsDetail> _stockincardsdetails;
        public virtual ICollection<StockInCardsDetail> StockInCardsDetails { get { return _stockincardsdetails; } set { SetNotifyingProperty(ref _stockincardsdetails, value); } }
    	private ICollection<StockMovementDetail> _stockmovementdetails;
        public virtual ICollection<StockMovementDetail> StockMovementDetails { get { return _stockmovementdetails; } set { SetNotifyingProperty(ref _stockmovementdetails, value); } }
    	private ICollection<StockOutCardsDetail> _stockoutcardsdetails;
        public virtual ICollection<StockOutCardsDetail> StockOutCardsDetails { get { return _stockoutcardsdetails; } set { SetNotifyingProperty(ref _stockoutcardsdetails, value); } }
    	private ICollection<SubGood> _subgoods;
        public virtual ICollection<SubGood> SubGoods { get { return _subgoods; } set { SetNotifyingProperty(ref _subgoods, value); } }
    	private ICollection<SubGood> _subgoods1;
        public virtual ICollection<SubGood> SubGoods1 { get { return _subgoods1; } set { SetNotifyingProperty(ref _subgoods1, value); } }
    	private ICollection<WorkOrderDetail> _workorderdetails;
        public virtual ICollection<WorkOrderDetail> WorkOrderDetails { get { return _workorderdetails; } set { SetNotifyingProperty(ref _workorderdetails, value); } }
    	private ICollection<WorkOrder> _workorders;
        public virtual ICollection<WorkOrder> WorkOrders { get { return _workorders; } set { SetNotifyingProperty(ref _workorders, value); } }
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    	private Account _account1;
        public virtual Account Account1 { get { return _account1; } set { SetNotifyingProperty(ref _account1, value); } }
    	private ICollection<AllocWO> _allocwoes;
        public virtual ICollection<AllocWO> AllocWOes { get { return _allocwoes; } set { SetNotifyingProperty(ref _allocwoes, value); } }
    	private ICollection<AllocWOItemDetail> _allocwoitemdetails;
        public virtual ICollection<AllocWOItemDetail> AllocWOItemDetails { get { return _allocwoitemdetails; } set { SetNotifyingProperty(ref _allocwoitemdetails, value); } }
    }
}
