//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetail : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _journalid;
        public int JournalID { get { return _journalid; } set { SetNotifyingProperty(ref _journalid, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<int> _accountid;
        public Nullable<int> AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private Nullable<int> _taxrateid;
        public Nullable<int> TaxRateID { get { return _taxrateid; } set { SetNotifyingProperty(ref _taxrateid, value); } }
    	private Nullable<double> _debit;
        public Nullable<double> Debit { get { return _debit; } set { SetNotifyingProperty(ref _debit, value); } }
    	private Nullable<double> _credit;
        public Nullable<double> Credit { get { return _credit; } set { SetNotifyingProperty(ref _credit, value); } }
    
    	private Journal _journal;
        public virtual Journal Journal { get { return _journal; } set { SetNotifyingProperty(ref _journal, value); } }
    	private TaxRate _taxrate;
        public virtual TaxRate TaxRate { get { return _taxrate; } set { SetNotifyingProperty(ref _taxrate, value); } }
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    }
}
