//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal : Entity
    {
        public Journal()
        {
            this.JournalDetails = new HashSet<JournalDetail>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _narration;
        public string Narration { get { return _narration; } set { SetNotifyingProperty(ref _narration, value); } }
    	private Nullable<int> _journaltype;
        public Nullable<int> JournalType { get { return _journaltype; } set { SetNotifyingProperty(ref _journaltype, value); } }
    	private Nullable<System.DateTime> _date;
        public Nullable<System.DateTime> Date { get { return _date; } set { SetNotifyingProperty(ref _date, value); } }
    	private Nullable<System.DateTime> _autoreversingdate;
        public Nullable<System.DateTime> AutoReversingDate { get { return _autoreversingdate; } set { SetNotifyingProperty(ref _autoreversingdate, value); } }
    	private Nullable<bool> _tojournalline;
        public Nullable<bool> ToJournalLine { get { return _tojournalline; } set { SetNotifyingProperty(ref _tojournalline, value); } }
    	private Nullable<bool> _showoncashbasisreport;
        public Nullable<bool> ShowOnCashBasisReport { get { return _showoncashbasisreport; } set { SetNotifyingProperty(ref _showoncashbasisreport, value); } }
    	private Nullable<bool> _vat;
        public Nullable<bool> VAT { get { return _vat; } set { SetNotifyingProperty(ref _vat, value); } }
    	private Nullable<double> _subtotal;
        public Nullable<double> SubTotal { get { return _subtotal; } set { SetNotifyingProperty(ref _subtotal, value); } }
    	private Nullable<double> _tax;
        public Nullable<double> Tax { get { return _tax; } set { SetNotifyingProperty(ref _tax, value); } }
    	private Nullable<double> _total;
        public Nullable<double> Total { get { return _total; } set { SetNotifyingProperty(ref _total, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private Nullable<int> _createduserid;
        public Nullable<int> CreatedUserID { get { return _createduserid; } set { SetNotifyingProperty(ref _createduserid, value); } }
    	private Nullable<int> _postedbyuserid;
        public Nullable<int> PostedByUserID { get { return _postedbyuserid; } set { SetNotifyingProperty(ref _postedbyuserid, value); } }
    	private Nullable<System.DateTime> _posteddate;
        public Nullable<System.DateTime> PostedDate { get { return _posteddate; } set { SetNotifyingProperty(ref _posteddate, value); } }
    	private Nullable<int> _companyid;
        public Nullable<int> CompanyID { get { return _companyid; } set { SetNotifyingProperty(ref _companyid, value); } }
    
    	private Company _company;
        public virtual Company Company { get { return _company; } set { SetNotifyingProperty(ref _company, value); } }
    	private ICollection<JournalDetail> _journaldetails;
        public virtual ICollection<JournalDetail> JournalDetails { get { return _journaldetails; } set { SetNotifyingProperty(ref _journaldetails, value); } }
    	private User _user;
        public virtual User User { get { return _user; } set { SetNotifyingProperty(ref _user, value); } }
    	private User _user1;
        public virtual User User1 { get { return _user1; } set { SetNotifyingProperty(ref _user1, value); } }
    }
}
