//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineHistory : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _machineid;
        public int MachineID { get { return _machineid; } set { SetNotifyingProperty(ref _machineid, value); } }
    	private int _workcenterid;
        public int WorkCenterID { get { return _workcenterid; } set { SetNotifyingProperty(ref _workcenterid, value); } }
    	private int _maxdailyruntime;
        public int MaxDailyRuntime { get { return _maxdailyruntime; } set { SetNotifyingProperty(ref _maxdailyruntime, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private int _status;
        public int Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private System.DateTime _updateddate;
        public System.DateTime UpdatedDate { get { return _updateddate; } set { SetNotifyingProperty(ref _updateddate, value); } }
    	private double _costs;
        public double Costs { get { return _costs; } set { SetNotifyingProperty(ref _costs, value); } }
    	private int _currencyid;
        public int CurrencyID { get { return _currencyid; } set { SetNotifyingProperty(ref _currencyid, value); } }
    }
}
