//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine : Entity
    {
        public Machine()
        {
            this.ProductionMonitors = new HashSet<ProductionMonitor>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private int _workcenterid;
        public int WorkCenterID { get { return _workcenterid; } set { SetNotifyingProperty(ref _workcenterid, value); } }
    	private System.DateTime _defaultsetuptime;
        public System.DateTime DefaultSetupTime { get { return _defaultsetuptime; } set { SetNotifyingProperty(ref _defaultsetuptime, value); } }
    	private double _defaultruntime;
        public double DefaultRunTime { get { return _defaultruntime; } set { SetNotifyingProperty(ref _defaultruntime, value); } }
    	private double _costperminute;
        public double CostPerMinute { get { return _costperminute; } set { SetNotifyingProperty(ref _costperminute, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    
    	private WorkCenter _workcenter;
        public virtual WorkCenter WorkCenter { get { return _workcenter; } set { SetNotifyingProperty(ref _workcenter, value); } }
    	private ICollection<ProductionMonitor> _productionmonitors;
        public virtual ICollection<ProductionMonitor> ProductionMonitors { get { return _productionmonitors; } set { SetNotifyingProperty(ref _productionmonitors, value); } }
    }
}
