//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _notefromid;
        public int NoteFromID { get { return _notefromid; } set { SetNotifyingProperty(ref _notefromid, value); } }
    	private Nullable<int> _createduserid;
        public Nullable<int> CreatedUserID { get { return _createduserid; } set { SetNotifyingProperty(ref _createduserid, value); } }
    	private System.DateTime _createddate;
        public System.DateTime CreatedDate { get { return _createddate; } set { SetNotifyingProperty(ref _createddate, value); } }
    	private string _note1;
        public string Note1 { get { return _note1; } set { SetNotifyingProperty(ref _note1, value); } }
    	private int _type;
        public int Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private string _changes;
        public string Changes { get { return _changes; } set { SetNotifyingProperty(ref _changes, value); } }
    	private Nullable<System.DateTime> _expectedpaymentdate;
        public Nullable<System.DateTime> ExpectedPaymentDate { get { return _expectedpaymentdate; } set { SetNotifyingProperty(ref _expectedpaymentdate, value); } }
    
    	private User _user;
        public virtual User User { get { return _user; } set { SetNotifyingProperty(ref _user, value); } }
    }
}
