//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayItem : Entity
    {
        public PayItem()
        {
            this.PaymentForPayItems = new HashSet<PaymentForPayItem>();
            this.PayRunEmployeeDetails = new HashSet<PayRunEmployeeDetail>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private Nullable<int> _type;
        public Nullable<int> Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    	private int _accountid;
        public int AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private Nullable<int> _showonslip;
        public Nullable<int> ShowOnSlip { get { return _showonslip; } set { SetNotifyingProperty(ref _showonslip, value); } }
    	private string _paidto;
        public string PaidTo { get { return _paidto; } set { SetNotifyingProperty(ref _paidto, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<int> _payitemtypeid;
        public Nullable<int> PayItemTypeID { get { return _payitemtypeid; } set { SetNotifyingProperty(ref _payitemtypeid, value); } }
    	private Nullable<double> _defaultrate;
        public Nullable<double> DefaultRate { get { return _defaultrate; } set { SetNotifyingProperty(ref _defaultrate, value); } }
    	private Nullable<bool> _isshow;
        public Nullable<bool> IsShow { get { return _isshow; } set { SetNotifyingProperty(ref _isshow, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    
    	private PayItemType _payitemtype;
        public virtual PayItemType PayItemType { get { return _payitemtype; } set { SetNotifyingProperty(ref _payitemtype, value); } }
    	private ICollection<PaymentForPayItem> _paymentforpayitems;
        public virtual ICollection<PaymentForPayItem> PaymentForPayItems { get { return _paymentforpayitems; } set { SetNotifyingProperty(ref _paymentforpayitems, value); } }
    	private ICollection<PayRunEmployeeDetail> _payrunemployeedetails;
        public virtual ICollection<PayRunEmployeeDetail> PayRunEmployeeDetails { get { return _payrunemployeedetails; } set { SetNotifyingProperty(ref _payrunemployeedetails, value); } }
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    }
}
