//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentForPayItem : Entity
    {
        public PaymentForPayItem()
        {
            this.Payments = new HashSet<Payment>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _payrunid;
        public int PayRunID { get { return _payrunid; } set { SetNotifyingProperty(ref _payrunid, value); } }
    	private int _payitemid;
        public int PayItemID { get { return _payitemid; } set { SetNotifyingProperty(ref _payitemid, value); } }
    	private Nullable<double> _amount;
        public Nullable<double> Amount { get { return _amount; } set { SetNotifyingProperty(ref _amount, value); } }
    	private Nullable<double> _payment;
        public Nullable<double> Payment { get { return _payment; } set { SetNotifyingProperty(ref _payment, value); } }
    	private Nullable<double> _remainamount;
        public Nullable<double> RemainAmount { get { return _remainamount; } set { SetNotifyingProperty(ref _remainamount, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private Nullable<System.DateTime> _duedate;
        public Nullable<System.DateTime> DueDate { get { return _duedate; } set { SetNotifyingProperty(ref _duedate, value); } }
    
    	private PayRun _payrun;
        public virtual PayRun PayRun { get { return _payrun; } set { SetNotifyingProperty(ref _payrun, value); } }
    	private ICollection<Payment> _payments;
        public virtual ICollection<Payment> Payments { get { return _payments; } set { SetNotifyingProperty(ref _payments, value); } }
    	private PayItem _payitem;
        public virtual PayItem PayItem { get { return _payitem; } set { SetNotifyingProperty(ref _payitem, value); } }
    }
}
