//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private Nullable<System.DateTime> _createddate;
        public Nullable<System.DateTime> CreatedDate { get { return _createddate; } set { SetNotifyingProperty(ref _createddate, value); } }
    	private Nullable<int> _createduserid;
        public Nullable<int> CreatedUserID { get { return _createduserid; } set { SetNotifyingProperty(ref _createduserid, value); } }
    	private Nullable<int> _approvaluserid;
        public Nullable<int> ApprovalUserID { get { return _approvaluserid; } set { SetNotifyingProperty(ref _approvaluserid, value); } }
    	private Nullable<int> _saleinvoiceid;
        public Nullable<int> SaleInvoiceID { get { return _saleinvoiceid; } set { SetNotifyingProperty(ref _saleinvoiceid, value); } }
    	private Nullable<int> _purchaseid;
        public Nullable<int> PurchaseID { get { return _purchaseid; } set { SetNotifyingProperty(ref _purchaseid, value); } }
    	private Nullable<int> _expenseclaimid;
        public Nullable<int> ExpenseClaimID { get { return _expenseclaimid; } set { SetNotifyingProperty(ref _expenseclaimid, value); } }
    	private Nullable<int> _paymentforpayitemid;
        public Nullable<int> PaymentForPayItemID { get { return _paymentforpayitemid; } set { SetNotifyingProperty(ref _paymentforpayitemid, value); } }
    	private Nullable<int> _payrunemployeeid;
        public Nullable<int> PayRunEmployeeID { get { return _payrunemployeeid; } set { SetNotifyingProperty(ref _payrunemployeeid, value); } }
    	private string _paymetnto;
        public string PaymetnTo { get { return _paymetnto; } set { SetNotifyingProperty(ref _paymetnto, value); } }
    	private double _totalmoney;
        public double TotalMoney { get { return _totalmoney; } set { SetNotifyingProperty(ref _totalmoney, value); } }
    	private int _currencyid;
        public int CurrencyID { get { return _currencyid; } set { SetNotifyingProperty(ref _currencyid, value); } }
    	private System.DateTime _datepaid;
        public System.DateTime DatePaid { get { return _datepaid; } set { SetNotifyingProperty(ref _datepaid, value); } }
    	private int _paytoaccount;
        public int PayToAccount { get { return _paytoaccount; } set { SetNotifyingProperty(ref _paytoaccount, value); } }
    	private string _reference;
        public string Reference { get { return _reference; } set { SetNotifyingProperty(ref _reference, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    
    	private Currency _currency;
        public virtual Currency Currency { get { return _currency; } set { SetNotifyingProperty(ref _currency, value); } }
    	private ExpenseClaim _expenseclaim;
        public virtual ExpenseClaim ExpenseClaim { get { return _expenseclaim; } set { SetNotifyingProperty(ref _expenseclaim, value); } }
    	private PaymentForPayItem _paymentforpayitem;
        public virtual PaymentForPayItem PaymentForPayItem { get { return _paymentforpayitem; } set { SetNotifyingProperty(ref _paymentforpayitem, value); } }
    	private PayRunEmployee _payrunemployee;
        public virtual PayRunEmployee PayRunEmployee { get { return _payrunemployee; } set { SetNotifyingProperty(ref _payrunemployee, value); } }
    	private Purchase _purchase;
        public virtual Purchase Purchase { get { return _purchase; } set { SetNotifyingProperty(ref _purchase, value); } }
    	private SaleInvoice _saleinvoice;
        public virtual SaleInvoice SaleInvoice { get { return _saleinvoice; } set { SetNotifyingProperty(ref _saleinvoice, value); } }
    	private User _user;
        public virtual User User { get { return _user; } set { SetNotifyingProperty(ref _user, value); } }
    	private User _user1;
        public virtual User User1 { get { return _user1; } set { SetNotifyingProperty(ref _user1, value); } }
    }
}
