//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRunEmployee : Entity
    {
        public PayRunEmployee()
        {
            this.Payments = new HashSet<Payment>();
            this.PayRunEmployeeDetails = new HashSet<PayRunEmployeeDetail>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _payrunid;
        public int PayRunID { get { return _payrunid; } set { SetNotifyingProperty(ref _payrunid, value); } }
    	private int _employeeid;
        public int EmployeeID { get { return _employeeid; } set { SetNotifyingProperty(ref _employeeid, value); } }
    	private Nullable<bool> _active;
        public Nullable<bool> Active { get { return _active; } set { SetNotifyingProperty(ref _active, value); } }
    	private Nullable<double> _amount;
        public Nullable<double> Amount { get { return _amount; } set { SetNotifyingProperty(ref _amount, value); } }
    	private Nullable<double> _payment;
        public Nullable<double> Payment { get { return _payment; } set { SetNotifyingProperty(ref _payment, value); } }
    	private Nullable<double> _remainamount;
        public Nullable<double> RemainAmount { get { return _remainamount; } set { SetNotifyingProperty(ref _remainamount, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private string _payslipnotes;
        public string PayslipNotes { get { return _payslipnotes; } set { SetNotifyingProperty(ref _payslipnotes, value); } }
    	private Nullable<bool> _showemployeetax;
        public Nullable<bool> ShowEmployeeTax { get { return _showemployeetax; } set { SetNotifyingProperty(ref _showemployeetax, value); } }
    
    	private PayRun _payrun;
        public virtual PayRun PayRun { get { return _payrun; } set { SetNotifyingProperty(ref _payrun, value); } }
    	private ICollection<Payment> _payments;
        public virtual ICollection<Payment> Payments { get { return _payments; } set { SetNotifyingProperty(ref _payments, value); } }
    	private ICollection<PayRunEmployeeDetail> _payrunemployeedetails;
        public virtual ICollection<PayRunEmployeeDetail> PayRunEmployeeDetails { get { return _payrunemployeedetails; } set { SetNotifyingProperty(ref _payrunemployeedetails, value); } }
    	private Employee _employee;
        public virtual Employee Employee { get { return _employee; } set { SetNotifyingProperty(ref _employee, value); } }
    }
}
