//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRun : Entity
    {
        public PayRun()
        {
            this.PayRunEmployees = new HashSet<PayRunEmployee>();
            this.PaymentForPayItems = new HashSet<PaymentForPayItem>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private Nullable<int> _numofemployee;
        public Nullable<int> NumOfEmployee { get { return _numofemployee; } set { SetNotifyingProperty(ref _numofemployee, value); } }
    	private Nullable<int> _employeepayment;
        public Nullable<int> EmployeePayment { get { return _employeepayment; } set { SetNotifyingProperty(ref _employeepayment, value); } }
    	private Nullable<int> _otherpayment;
        public Nullable<int> OtherPayment { get { return _otherpayment; } set { SetNotifyingProperty(ref _otherpayment, value); } }
    	private Nullable<double> _total;
        public Nullable<double> Total { get { return _total; } set { SetNotifyingProperty(ref _total, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private Nullable<int> _createduserid;
        public Nullable<int> CreatedUserID { get { return _createduserid; } set { SetNotifyingProperty(ref _createduserid, value); } }
    	private Nullable<int> _approvaluserid;
        public Nullable<int> ApprovalUserID { get { return _approvaluserid; } set { SetNotifyingProperty(ref _approvaluserid, value); } }
    	private Nullable<int> _payfrequency;
        public Nullable<int> PayFrequency { get { return _payfrequency; } set { SetNotifyingProperty(ref _payfrequency, value); } }
    	private Nullable<System.DateTime> _fromdate;
        public Nullable<System.DateTime> FromDate { get { return _fromdate; } set { SetNotifyingProperty(ref _fromdate, value); } }
    	private Nullable<System.DateTime> _todate;
        public Nullable<System.DateTime> ToDate { get { return _todate; } set { SetNotifyingProperty(ref _todate, value); } }
    	private Nullable<System.DateTime> _paymentdate;
        public Nullable<System.DateTime> PaymentDate { get { return _paymentdate; } set { SetNotifyingProperty(ref _paymentdate, value); } }
    	private Nullable<int> _companyid;
        public Nullable<int> CompanyID { get { return _companyid; } set { SetNotifyingProperty(ref _companyid, value); } }
    	private Nullable<System.DateTime> _approvaldate;
        public Nullable<System.DateTime> ApprovalDate { get { return _approvaldate; } set { SetNotifyingProperty(ref _approvaldate, value); } }
    	private Nullable<double> _remainmoney;
        public Nullable<double> RemainMoney { get { return _remainmoney; } set { SetNotifyingProperty(ref _remainmoney, value); } }
    
    	private ICollection<PayRunEmployee> _payrunemployees;
        public virtual ICollection<PayRunEmployee> PayRunEmployees { get { return _payrunemployees; } set { SetNotifyingProperty(ref _payrunemployees, value); } }
    	private User _user;
        public virtual User User { get { return _user; } set { SetNotifyingProperty(ref _user, value); } }
    	private User _user1;
        public virtual User User1 { get { return _user1; } set { SetNotifyingProperty(ref _user1, value); } }
    	private ICollection<PaymentForPayItem> _paymentforpayitems;
        public virtual ICollection<PaymentForPayItem> PaymentForPayItems { get { return _paymentforpayitems; } set { SetNotifyingProperty(ref _paymentforpayitems, value); } }
    	private Company _company;
        public virtual Company Company { get { return _company; } set { SetNotifyingProperty(ref _company, value); } }
    }
}
