//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRunEmployeeDetail : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _payrunemployeeid;
        public int PayRunEmployeeID { get { return _payrunemployeeid; } set { SetNotifyingProperty(ref _payrunemployeeid, value); } }
    	private int _quantity;
        public int Quantity { get { return _quantity; } set { SetNotifyingProperty(ref _quantity, value); } }
    	private Nullable<double> _rate;
        public Nullable<double> Rate { get { return _rate; } set { SetNotifyingProperty(ref _rate, value); } }
    	private Nullable<double> _amount;
        public Nullable<double> Amount { get { return _amount; } set { SetNotifyingProperty(ref _amount, value); } }
    	private Nullable<double> _totalpay;
        public Nullable<double> TotalPay { get { return _totalpay; } set { SetNotifyingProperty(ref _totalpay, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private int _payitemid;
        public int PayItemID { get { return _payitemid; } set { SetNotifyingProperty(ref _payitemid, value); } }
    
    	private PayRunEmployee _payrunemployee;
        public virtual PayRunEmployee PayRunEmployee { get { return _payrunemployee; } set { SetNotifyingProperty(ref _payrunemployee, value); } }
    	private PayItem _payitem;
        public virtual PayItem PayItem { get { return _payitem; } set { SetNotifyingProperty(ref _payitem, value); } }
    }
}
