//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessMachine : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private Nullable<int> _machineid;
        public Nullable<int> MachineID { get { return _machineid; } set { SetNotifyingProperty(ref _machineid, value); } }
    	private Nullable<int> _goodprocessid;
        public Nullable<int> GoodProcessID { get { return _goodprocessid; } set { SetNotifyingProperty(ref _goodprocessid, value); } }
    	private Nullable<int> _goodid;
        public Nullable<int> GoodID { get { return _goodid; } set { SetNotifyingProperty(ref _goodid, value); } }
    	private Nullable<int> _workingminute;
        public Nullable<int> WorkingMinute { get { return _workingminute; } set { SetNotifyingProperty(ref _workingminute, value); } }
    	private Nullable<int> _costperminute;
        public Nullable<int> CostPerMinute { get { return _costperminute; } set { SetNotifyingProperty(ref _costperminute, value); } }
    }
}
