//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _goodid;
        public int GoodID { get { return _goodid; } set { SetNotifyingProperty(ref _goodid, value); } }
    	private int _uomid;
        public int UOMID { get { return _uomid; } set { SetNotifyingProperty(ref _uomid, value); } }
    	private int _purchaseid;
        public int PurchaseID { get { return _purchaseid; } set { SetNotifyingProperty(ref _purchaseid, value); } }
    	private int _quantity;
        public int Quantity { get { return _quantity; } set { SetNotifyingProperty(ref _quantity, value); } }
    	private double _price;
        public double Price { get { return _price; } set { SetNotifyingProperty(ref _price, value); } }
    	private Nullable<int> _accountid;
        public Nullable<int> AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private Nullable<int> _taxrateid;
        public Nullable<int> TaxRateID { get { return _taxrateid; } set { SetNotifyingProperty(ref _taxrateid, value); } }
    	private Nullable<double> _discount;
        public Nullable<double> Discount { get { return _discount; } set { SetNotifyingProperty(ref _discount, value); } }
    	private double _totalmoney;
        public double TotalMoney { get { return _totalmoney; } set { SetNotifyingProperty(ref _totalmoney, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    
    	private TaxRate _taxrate;
        public virtual TaxRate TaxRate { get { return _taxrate; } set { SetNotifyingProperty(ref _taxrate, value); } }
    	private UOM _uom;
        public virtual UOM UOM { get { return _uom; } set { SetNotifyingProperty(ref _uom, value); } }
    	private Purchase _purchase;
        public virtual Purchase Purchase { get { return _purchase; } set { SetNotifyingProperty(ref _purchase, value); } }
    	private Good _good;
        public virtual Good Good { get { return _good; } set { SetNotifyingProperty(ref _good, value); } }
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    }
}
