//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repeating : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _numdayrepeat;
        public int NumDayRepeat { get { return _numdayrepeat; } set { SetNotifyingProperty(ref _numdayrepeat, value); } }
    	private int _repeattime;
        public int RepeatTime { get { return _repeattime; } set { SetNotifyingProperty(ref _repeattime, value); } }
    	private System.DateTime _daterun;
        public System.DateTime DateRun { get { return _daterun; } set { SetNotifyingProperty(ref _daterun, value); } }
    	private int _duedatenum;
        public int DueDateNum { get { return _duedatenum; } set { SetNotifyingProperty(ref _duedatenum, value); } }
    	private int _duedatetypeid;
        public int DueDateTypeID { get { return _duedatetypeid; } set { SetNotifyingProperty(ref _duedatetypeid, value); } }
    	private Nullable<System.DateTime> _enddate;
        public Nullable<System.DateTime> EndDate { get { return _enddate; } set { SetNotifyingProperty(ref _enddate, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private Nullable<int> _repeattype;
        public Nullable<int> RepeatType { get { return _repeattype; } set { SetNotifyingProperty(ref _repeattype, value); } }
    	private Nullable<int> _saleinvoiceid;
        public Nullable<int> SaleInvoiceID { get { return _saleinvoiceid; } set { SetNotifyingProperty(ref _saleinvoiceid, value); } }
    	private Nullable<int> _purchaseid;
        public Nullable<int> PurchaseID { get { return _purchaseid; } set { SetNotifyingProperty(ref _purchaseid, value); } }
    
    	private Purchase _purchase;
        public virtual Purchase Purchase { get { return _purchase; } set { SetNotifyingProperty(ref _purchase, value); } }
    	private SaleInvoice _saleinvoice;
        public virtual SaleInvoice SaleInvoice { get { return _saleinvoice; } set { SetNotifyingProperty(ref _saleinvoice, value); } }
    }
}
