//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role : Entity
    {
        public Role()
        {
            this.UsersInRoles = new HashSet<UsersInRole>();
            this.ControlInRoles = new HashSet<ControlInRole>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _rolename;
        public string RoleName { get { return _rolename; } set { SetNotifyingProperty(ref _rolename, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    
    	private ICollection<UsersInRole> _usersinroles;
        public virtual ICollection<UsersInRole> UsersInRoles { get { return _usersinroles; } set { SetNotifyingProperty(ref _usersinroles, value); } }
    	private RoleFunction _rolefunction;
        public virtual RoleFunction RoleFunction { get { return _rolefunction; } set { SetNotifyingProperty(ref _rolefunction, value); } }
    	private RolePermission _rolepermission;
        public virtual RolePermission RolePermission { get { return _rolepermission; } set { SetNotifyingProperty(ref _rolepermission, value); } }
    	private ICollection<ControlInRole> _controlinroles;
        public virtual ICollection<ControlInRole> ControlInRoles { get { return _controlinroles; } set { SetNotifyingProperty(ref _controlinroles, value); } }
    }
}
