//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private Nullable<bool> _createbilldraft;
        public Nullable<bool> CreateBillDraft { get { return _createbilldraft; } set { SetNotifyingProperty(ref _createbilldraft, value); } }
    	private Nullable<bool> _viewandeditbill;
        public Nullable<bool> ViewAndEditBill { get { return _viewandeditbill; } set { SetNotifyingProperty(ref _viewandeditbill, value); } }
    	private Nullable<bool> _editbillcreatedbyother;
        public Nullable<bool> EditBillCreatedByOther { get { return _editbillcreatedbyother; } set { SetNotifyingProperty(ref _editbillcreatedbyother, value); } }
    	private Nullable<bool> _deletebill;
        public Nullable<bool> DeleteBill { get { return _deletebill; } set { SetNotifyingProperty(ref _deletebill, value); } }
    	private Nullable<bool> _deletebillcreatedbyother;
        public Nullable<bool> DeleteBillCreatedByOther { get { return _deletebillcreatedbyother; } set { SetNotifyingProperty(ref _deletebillcreatedbyother, value); } }
    	private Nullable<bool> _approvebill;
        public Nullable<bool> ApproveBill { get { return _approvebill; } set { SetNotifyingProperty(ref _approvebill, value); } }
    	private Nullable<bool> _workordercreate;
        public Nullable<bool> WorkOrderCreate { get { return _workordercreate; } set { SetNotifyingProperty(ref _workordercreate, value); } }
    	private Nullable<bool> _dobatchpayment;
        public Nullable<bool> DoBatchPayment { get { return _dobatchpayment; } set { SetNotifyingProperty(ref _dobatchpayment, value); } }
    	private Nullable<bool> _addnotetobill;
        public Nullable<bool> AddNoteToBill { get { return _addnotetobill; } set { SetNotifyingProperty(ref _addnotetobill, value); } }
    	private Nullable<bool> _repeatingbill;
        public Nullable<bool> RepeatingBill { get { return _repeatingbill; } set { SetNotifyingProperty(ref _repeatingbill, value); } }
    	private Nullable<bool> _createinvoicedraft;
        public Nullable<bool> CreateInvoiceDraft { get { return _createinvoicedraft; } set { SetNotifyingProperty(ref _createinvoicedraft, value); } }
    	private Nullable<bool> _viewandeditinvoice;
        public Nullable<bool> ViewAndEditInvoice { get { return _viewandeditinvoice; } set { SetNotifyingProperty(ref _viewandeditinvoice, value); } }
    	private Nullable<bool> _editinvoicecreatedbyother;
        public Nullable<bool> EditInvoiceCreatedByOther { get { return _editinvoicecreatedbyother; } set { SetNotifyingProperty(ref _editinvoicecreatedbyother, value); } }
    	private Nullable<bool> _deleteinvoice;
        public Nullable<bool> DeleteInvoice { get { return _deleteinvoice; } set { SetNotifyingProperty(ref _deleteinvoice, value); } }
    	private Nullable<bool> _deleteinvoicecreatedbyother;
        public Nullable<bool> DeleteInvoiceCreatedByOther { get { return _deleteinvoicecreatedbyother; } set { SetNotifyingProperty(ref _deleteinvoicecreatedbyother, value); } }
    	private Nullable<bool> _approveinvoice;
        public Nullable<bool> ApproveInvoice { get { return _approveinvoice; } set { SetNotifyingProperty(ref _approveinvoice, value); } }
    	private Nullable<bool> _recordtinvoicespaymen;
        public Nullable<bool> RecordtInvoicesPaymen { get { return _recordtinvoicespaymen; } set { SetNotifyingProperty(ref _recordtinvoicespaymen, value); } }
    	private Nullable<bool> _sendinvoicestatement;
        public Nullable<bool> SendInvoiceStatement { get { return _sendinvoicestatement; } set { SetNotifyingProperty(ref _sendinvoicestatement, value); } }
    	private Nullable<bool> _addnotetoinvoice;
        public Nullable<bool> AddNoteToInvoice { get { return _addnotetoinvoice; } set { SetNotifyingProperty(ref _addnotetoinvoice, value); } }
    	private Nullable<bool> _repeatinginvoice;
        public Nullable<bool> RepeatingInvoice { get { return _repeatinginvoice; } set { SetNotifyingProperty(ref _repeatinginvoice, value); } }
    	private Nullable<bool> _editinvoiceprice;
        public Nullable<bool> EditInvoicePrice { get { return _editinvoiceprice; } set { SetNotifyingProperty(ref _editinvoiceprice, value); } }
    	private Nullable<bool> _recordbillpayment;
        public Nullable<bool> RecordBillPayment { get { return _recordbillpayment; } set { SetNotifyingProperty(ref _recordbillpayment, value); } }
    	private Nullable<bool> _workorderapproval;
        public Nullable<bool> WorkOrderApproval { get { return _workorderapproval; } set { SetNotifyingProperty(ref _workorderapproval, value); } }
    	private Nullable<bool> _allocatecreate;
        public Nullable<bool> AllocateCreate { get { return _allocatecreate; } set { SetNotifyingProperty(ref _allocatecreate, value); } }
    	private Nullable<bool> _allocateapproval;
        public Nullable<bool> AllocateApproval { get { return _allocateapproval; } set { SetNotifyingProperty(ref _allocateapproval, value); } }
    	private Nullable<bool> _machineplanningcreate;
        public Nullable<bool> MachinePlanningCreate { get { return _machineplanningcreate; } set { SetNotifyingProperty(ref _machineplanningcreate, value); } }
    	private Nullable<bool> _planningcreate;
        public Nullable<bool> PlanningCreate { get { return _planningcreate; } set { SetNotifyingProperty(ref _planningcreate, value); } }
    	private Nullable<bool> _planningupdateprocess;
        public Nullable<bool> PlanningUpdateProcess { get { return _planningupdateprocess; } set { SetNotifyingProperty(ref _planningupdateprocess, value); } }
    	private Nullable<bool> _planningapproval;
        public Nullable<bool> PlanningApproval { get { return _planningapproval; } set { SetNotifyingProperty(ref _planningapproval, value); } }
    	private Nullable<int> _featureid;
        public Nullable<int> FeatureID { get { return _featureid; } set { SetNotifyingProperty(ref _featureid, value); } }
    
    	private Role _role;
        public virtual Role Role { get { return _role; } set { SetNotifyingProperty(ref _role, value); } }
    	private Feature _feature;
        public virtual Feature Feature { get { return _feature; } set { SetNotifyingProperty(ref _feature, value); } }
    }
}
