//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleFunction : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _roleid;
        public int RoleID { get { return _roleid; } set { SetNotifyingProperty(ref _roleid, value); } }
    	private int _subfunctionid;
        public int SubFunctionID { get { return _subfunctionid; } set { SetNotifyingProperty(ref _subfunctionid, value); } }
    
    	private SubFunction _subfunction;
        public virtual SubFunction SubFunction { get { return _subfunction; } set { SetNotifyingProperty(ref _subfunction, value); } }
    	private Role _role;
        public virtual Role Role { get { return _role; } set { SetNotifyingProperty(ref _role, value); } }
    }
}
