//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoice : Entity
    {
        public SaleInvoice()
        {
            this.SaleInvoiceDetails = new HashSet<SaleInvoiceDetail>();
            this.Repeatings = new HashSet<Repeating>();
            this.Payments = new HashSet<Payment>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private Nullable<int> _approvaluserid;
        public Nullable<int> ApprovalUserID { get { return _approvaluserid; } set { SetNotifyingProperty(ref _approvaluserid, value); } }
    	private int _createduserid;
        public int CreatedUserID { get { return _createduserid; } set { SetNotifyingProperty(ref _createduserid, value); } }
    	private Nullable<int> _contactid;
        public Nullable<int> ContactID { get { return _contactid; } set { SetNotifyingProperty(ref _contactid, value); } }
    	private string _contactname;
        public string ContactName { get { return _contactname; } set { SetNotifyingProperty(ref _contactname, value); } }
    	private System.DateTime _createddate;
        public System.DateTime CreatedDate { get { return _createddate; } set { SetNotifyingProperty(ref _createddate, value); } }
    	private Nullable<System.DateTime> _duedate;
        public Nullable<System.DateTime> DueDate { get { return _duedate; } set { SetNotifyingProperty(ref _duedate, value); } }
    	private string _reference;
        public string Reference { get { return _reference; } set { SetNotifyingProperty(ref _reference, value); } }
    	private Nullable<int> _currencyid;
        public Nullable<int> CurrencyID { get { return _currencyid; } set { SetNotifyingProperty(ref _currencyid, value); } }
    	private Nullable<double> _vat;
        public Nullable<double> VAT { get { return _vat; } set { SetNotifyingProperty(ref _vat, value); } }
    	private Nullable<int> _taxamounttype;
        public Nullable<int> TaxAmountType { get { return _taxamounttype; } set { SetNotifyingProperty(ref _taxamounttype, value); } }
    	private Nullable<double> _subtotal;
        public Nullable<double> SubTotal { get { return _subtotal; } set { SetNotifyingProperty(ref _subtotal, value); } }
    	private Nullable<double> _totaltax;
        public Nullable<double> TotalTax { get { return _totaltax; } set { SetNotifyingProperty(ref _totaltax, value); } }
    	private Nullable<double> _totalmoney;
        public Nullable<double> TotalMoney { get { return _totalmoney; } set { SetNotifyingProperty(ref _totalmoney, value); } }
    	private Nullable<int> _status;
        public Nullable<int> Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<int> _type;
        public Nullable<int> Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    	private Nullable<int> _usevat;
        public Nullable<int> UseVAT { get { return _usevat; } set { SetNotifyingProperty(ref _usevat, value); } }
    	private int _stockid;
        public int StockID { get { return _stockid; } set { SetNotifyingProperty(ref _stockid, value); } }
    	private Nullable<int> _companyid;
        public Nullable<int> CompanyID { get { return _companyid; } set { SetNotifyingProperty(ref _companyid, value); } }
    	private Nullable<System.DateTime> _approvaldate;
        public Nullable<System.DateTime> ApprovalDate { get { return _approvaldate; } set { SetNotifyingProperty(ref _approvaldate, value); } }
    	private Nullable<double> _remainmoney;
        public Nullable<double> RemainMoney { get { return _remainmoney; } set { SetNotifyingProperty(ref _remainmoney, value); } }
    
    	private Currency _currency;
        public virtual Currency Currency { get { return _currency; } set { SetNotifyingProperty(ref _currency, value); } }
    	private ICollection<SaleInvoiceDetail> _saleinvoicedetails;
        public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get { return _saleinvoicedetails; } set { SetNotifyingProperty(ref _saleinvoicedetails, value); } }
    	private User _user;
        public virtual User User { get { return _user; } set { SetNotifyingProperty(ref _user, value); } }
    	private User _user1;
        public virtual User User1 { get { return _user1; } set { SetNotifyingProperty(ref _user1, value); } }
    	private ICollection<Repeating> _repeatings;
        public virtual ICollection<Repeating> Repeatings { get { return _repeatings; } set { SetNotifyingProperty(ref _repeatings, value); } }
    	private Contact _contact;
        public virtual Contact Contact { get { return _contact; } set { SetNotifyingProperty(ref _contact, value); } }
    	private ICollection<Payment> _payments;
        public virtual ICollection<Payment> Payments { get { return _payments; } set { SetNotifyingProperty(ref _payments, value); } }
    	private Company _company;
        public virtual Company Company { get { return _company; } set { SetNotifyingProperty(ref _company, value); } }
    }
}
