//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoiceDetail : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _saleinvoiceid;
        public int SaleInvoiceID { get { return _saleinvoiceid; } set { SetNotifyingProperty(ref _saleinvoiceid, value); } }
    	private int _goodid;
        public int GoodID { get { return _goodid; } set { SetNotifyingProperty(ref _goodid, value); } }
    	private Nullable<int> _uomid;
        public Nullable<int> UOMID { get { return _uomid; } set { SetNotifyingProperty(ref _uomid, value); } }
    	private int _quantity;
        public int Quantity { get { return _quantity; } set { SetNotifyingProperty(ref _quantity, value); } }
    	private Nullable<double> _price;
        public Nullable<double> Price { get { return _price; } set { SetNotifyingProperty(ref _price, value); } }
    	private Nullable<int> _taxrateid;
        public Nullable<int> TaxRateID { get { return _taxrateid; } set { SetNotifyingProperty(ref _taxrateid, value); } }
    	private Nullable<double> _discount;
        public Nullable<double> Discount { get { return _discount; } set { SetNotifyingProperty(ref _discount, value); } }
    	private Nullable<double> _subtotal;
        public Nullable<double> Subtotal { get { return _subtotal; } set { SetNotifyingProperty(ref _subtotal, value); } }
    	private Nullable<int> _accountid;
        public Nullable<int> AccountID { get { return _accountid; } set { SetNotifyingProperty(ref _accountid, value); } }
    	private Nullable<double> _totalmoney;
        public Nullable<double> TotalMoney { get { return _totalmoney; } set { SetNotifyingProperty(ref _totalmoney, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    
    	private TaxRate _taxrate;
        public virtual TaxRate TaxRate { get { return _taxrate; } set { SetNotifyingProperty(ref _taxrate, value); } }
    	private UOM _uom;
        public virtual UOM UOM { get { return _uom; } set { SetNotifyingProperty(ref _uom, value); } }
    	private SaleInvoice _saleinvoice;
        public virtual SaleInvoice SaleInvoice { get { return _saleinvoice; } set { SetNotifyingProperty(ref _saleinvoice, value); } }
    	private Good _good;
        public virtual Good Good { get { return _good; } set { SetNotifyingProperty(ref _good, value); } }
    	private Account _account;
        public virtual Account Account { get { return _account; } set { SetNotifyingProperty(ref _account, value); } }
    	private Account _account1;
        public virtual Account Account1 { get { return _account1; } set { SetNotifyingProperty(ref _account1, value); } }
    }
}
