//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoiceSetting : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private Nullable<int> _billdefaultduedate;
        public Nullable<int> BillDefaultDueDate { get { return _billdefaultduedate; } set { SetNotifyingProperty(ref _billdefaultduedate, value); } }
    	private Nullable<int> _saleinvoicedefaultduedate;
        public Nullable<int> SaleInvoiceDefaultDueDate { get { return _saleinvoicedefaultduedate; } set { SetNotifyingProperty(ref _saleinvoicedefaultduedate, value); } }
    	private string _invoiceprefix;
        public string InvoicePrefix { get { return _invoiceprefix; } set { SetNotifyingProperty(ref _invoiceprefix, value); } }
    	private string _creditnoteprefix;
        public string CreditNotePrefix { get { return _creditnoteprefix; } set { SetNotifyingProperty(ref _creditnoteprefix, value); } }
    	private string _nextnumber;
        public string NextNumber { get { return _nextnumber; } set { SetNotifyingProperty(ref _nextnumber, value); } }
    	private Nullable<int> _billdefaulttypeid;
        public Nullable<int> BillDefaultTypeID { get { return _billdefaulttypeid; } set { SetNotifyingProperty(ref _billdefaulttypeid, value); } }
    	private Nullable<int> _saleinvoicedefaulttypeid;
        public Nullable<int> SaleInvoiceDefaultTypeID { get { return _saleinvoicedefaulttypeid; } set { SetNotifyingProperty(ref _saleinvoicedefaulttypeid, value); } }
    	private Nullable<int> _type;
        public Nullable<int> Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    
    	private DueDateType _duedatetype;
        public virtual DueDateType DueDateType { get { return _duedatetype; } set { SetNotifyingProperty(ref _duedatetype, value); } }
    	private DueDateType _duedatetype1;
        public virtual DueDateType DueDateType1 { get { return _duedatetype1; } set { SetNotifyingProperty(ref _duedatetype1, value); } }
    }
}
