//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock : Entity
    {
        public Stock()
        {
            this.StockInCards = new HashSet<StockInCard>();
            this.StockOutCards = new HashSet<StockOutCard>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.StockMovements = new HashSet<StockMovement>();
            this.StockMovements1 = new HashSet<StockMovement>();
            this.AllocWOes = new HashSet<AllocWO>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private Nullable<int> _currentcompanyid;
        public Nullable<int> CurrentCompanyID { get { return _currentcompanyid; } set { SetNotifyingProperty(ref _currentcompanyid, value); } }
    	private Nullable<int> _maxquatity;
        public Nullable<int> MaxQuatity { get { return _maxquatity; } set { SetNotifyingProperty(ref _maxquatity, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private string _address;
        public string Address { get { return _address; } set { SetNotifyingProperty(ref _address, value); } }
    
    	private ICollection<StockInCard> _stockincards;
        public virtual ICollection<StockInCard> StockInCards { get { return _stockincards; } set { SetNotifyingProperty(ref _stockincards, value); } }
    	private ICollection<StockOutCard> _stockoutcards;
        public virtual ICollection<StockOutCard> StockOutCards { get { return _stockoutcards; } set { SetNotifyingProperty(ref _stockoutcards, value); } }
    	private ICollection<WorkOrder> _workorders;
        public virtual ICollection<WorkOrder> WorkOrders { get { return _workorders; } set { SetNotifyingProperty(ref _workorders, value); } }
    	private ICollection<StockMovement> _stockmovements;
        public virtual ICollection<StockMovement> StockMovements { get { return _stockmovements; } set { SetNotifyingProperty(ref _stockmovements, value); } }
    	private ICollection<StockMovement> _stockmovements1;
        public virtual ICollection<StockMovement> StockMovements1 { get { return _stockmovements1; } set { SetNotifyingProperty(ref _stockmovements1, value); } }
    	private ICollection<AllocWO> _allocwoes;
        public virtual ICollection<AllocWO> AllocWOes { get { return _allocwoes; } set { SetNotifyingProperty(ref _allocwoes, value); } }
    }
}
