//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovementDetail : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _stockmovementid;
        public int StockMovementID { get { return _stockmovementid; } set { SetNotifyingProperty(ref _stockmovementid, value); } }
    	private int _goodid;
        public int GoodID { get { return _goodid; } set { SetNotifyingProperty(ref _goodid, value); } }
    	private Nullable<System.DateTime> _datein;
        public Nullable<System.DateTime> DateIn { get { return _datein; } set { SetNotifyingProperty(ref _datein, value); } }
    	private int _uomid;
        public int UOMID { get { return _uomid; } set { SetNotifyingProperty(ref _uomid, value); } }
    	private int _quantity;
        public int Quantity { get { return _quantity; } set { SetNotifyingProperty(ref _quantity, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    
    	private UOM _uom;
        public virtual UOM UOM { get { return _uom; } set { SetNotifyingProperty(ref _uom, value); } }
    	private Good _good;
        public virtual Good Good { get { return _good; } set { SetNotifyingProperty(ref _good, value); } }
    	private StockMovement _stockmovement;
        public virtual StockMovement StockMovement { get { return _stockmovement; } set { SetNotifyingProperty(ref _stockmovement, value); } }
    }
}
