//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRate : Entity
    {
        public TaxRate()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.SaleInvoiceDetails = new HashSet<SaleInvoiceDetail>();
            this.BankAccountDetails = new HashSet<BankAccountDetail>();
            this.ExpenseClaimDetails = new HashSet<ExpenseClaimDetail>();
            this.ExpenseClaimDetails1 = new HashSet<ExpenseClaimDetail>();
            this.Contacts = new HashSet<Contact>();
            this.Contacts1 = new HashSet<Contact>();
            this.Goods = new HashSet<Good>();
            this.Goods1 = new HashSet<Good>();
            this.JournalDetails = new HashSet<JournalDetail>();
            this.Accounts = new HashSet<Account>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private Nullable<double> _rate;
        public Nullable<double> Rate { get { return _rate; } set { SetNotifyingProperty(ref _rate, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    
    	private ICollection<PurchaseDetail> _purchasedetails;
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get { return _purchasedetails; } set { SetNotifyingProperty(ref _purchasedetails, value); } }
    	private ICollection<SaleInvoiceDetail> _saleinvoicedetails;
        public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get { return _saleinvoicedetails; } set { SetNotifyingProperty(ref _saleinvoicedetails, value); } }
    	private ICollection<BankAccountDetail> _bankaccountdetails;
        public virtual ICollection<BankAccountDetail> BankAccountDetails { get { return _bankaccountdetails; } set { SetNotifyingProperty(ref _bankaccountdetails, value); } }
    	private ICollection<ExpenseClaimDetail> _expenseclaimdetails;
        public virtual ICollection<ExpenseClaimDetail> ExpenseClaimDetails { get { return _expenseclaimdetails; } set { SetNotifyingProperty(ref _expenseclaimdetails, value); } }
    	private ICollection<ExpenseClaimDetail> _expenseclaimdetails1;
        public virtual ICollection<ExpenseClaimDetail> ExpenseClaimDetails1 { get { return _expenseclaimdetails1; } set { SetNotifyingProperty(ref _expenseclaimdetails1, value); } }
    	private ICollection<Contact> _contacts;
        public virtual ICollection<Contact> Contacts { get { return _contacts; } set { SetNotifyingProperty(ref _contacts, value); } }
    	private ICollection<Contact> _contacts1;
        public virtual ICollection<Contact> Contacts1 { get { return _contacts1; } set { SetNotifyingProperty(ref _contacts1, value); } }
    	private ICollection<Good> _goods;
        public virtual ICollection<Good> Goods { get { return _goods; } set { SetNotifyingProperty(ref _goods, value); } }
    	private ICollection<Good> _goods1;
        public virtual ICollection<Good> Goods1 { get { return _goods1; } set { SetNotifyingProperty(ref _goods1, value); } }
    	private ICollection<JournalDetail> _journaldetails;
        public virtual ICollection<JournalDetail> JournalDetails { get { return _journaldetails; } set { SetNotifyingProperty(ref _journaldetails, value); } }
    	private ICollection<Account> _accounts;
        public virtual ICollection<Account> Accounts { get { return _accounts; } set { SetNotifyingProperty(ref _accounts, value); } }
    }
}
