//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOM : Entity
    {
        public UOM()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.SaleInvoiceDetails = new HashSet<SaleInvoiceDetail>();
            this.StockInCardsDetails = new HashSet<StockInCardsDetail>();
            this.StockMovementDetails = new HashSet<StockMovementDetail>();
            this.StockOutCardsDetails = new HashSet<StockOutCardsDetail>();
            this.Goods = new HashSet<Good>();
            this.AllocWOItemDetails = new HashSet<AllocWOItemDetail>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _name;
        public string Name { get { return _name; } set { SetNotifyingProperty(ref _name, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<int> _quantity;
        public Nullable<int> Quantity { get { return _quantity; } set { SetNotifyingProperty(ref _quantity, value); } }
    
    	private ICollection<PurchaseDetail> _purchasedetails;
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get { return _purchasedetails; } set { SetNotifyingProperty(ref _purchasedetails, value); } }
    	private ICollection<SaleInvoiceDetail> _saleinvoicedetails;
        public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get { return _saleinvoicedetails; } set { SetNotifyingProperty(ref _saleinvoicedetails, value); } }
    	private ICollection<StockInCardsDetail> _stockincardsdetails;
        public virtual ICollection<StockInCardsDetail> StockInCardsDetails { get { return _stockincardsdetails; } set { SetNotifyingProperty(ref _stockincardsdetails, value); } }
    	private ICollection<StockMovementDetail> _stockmovementdetails;
        public virtual ICollection<StockMovementDetail> StockMovementDetails { get { return _stockmovementdetails; } set { SetNotifyingProperty(ref _stockmovementdetails, value); } }
    	private ICollection<StockOutCardsDetail> _stockoutcardsdetails;
        public virtual ICollection<StockOutCardsDetail> StockOutCardsDetails { get { return _stockoutcardsdetails; } set { SetNotifyingProperty(ref _stockoutcardsdetails, value); } }
    	private ICollection<Good> _goods;
        public virtual ICollection<Good> Goods { get { return _goods; } set { SetNotifyingProperty(ref _goods, value); } }
    	private ICollection<AllocWOItemDetail> _allocwoitemdetails;
        public virtual ICollection<AllocWOItemDetail> AllocWOItemDetails { get { return _allocwoitemdetails; } set { SetNotifyingProperty(ref _allocwoitemdetails, value); } }
    }
}
