//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInRole : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _userid;
        public int UserID { get { return _userid; } set { SetNotifyingProperty(ref _userid, value); } }
    	private int _roleid;
        public int RoleID { get { return _roleid; } set { SetNotifyingProperty(ref _roleid, value); } }
    
    	private Role _role;
        public virtual Role Role { get { return _role; } set { SetNotifyingProperty(ref _role, value); } }
    	private User _user;
        public virtual User User { get { return _user; } set { SetNotifyingProperty(ref _user, value); } }
    }
}
