//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder : Entity
    {
        public WorkOrder()
        {
            this.WorkOrderDetails = new HashSet<WorkOrderDetail>();
            this.AllocWOes = new HashSet<AllocWO>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private System.DateTime _createddate;
        public System.DateTime CreatedDate { get { return _createddate; } set { SetNotifyingProperty(ref _createddate, value); } }
    	private Nullable<System.DateTime> _completeddate;
        public Nullable<System.DateTime> CompletedDate { get { return _completeddate; } set { SetNotifyingProperty(ref _completeddate, value); } }
    	private int _createduserid;
        public int CreatedUserID { get { return _createduserid; } set { SetNotifyingProperty(ref _createduserid, value); } }
    	private Nullable<int> _approvaluserid;
        public Nullable<int> ApprovalUserID { get { return _approvaluserid; } set { SetNotifyingProperty(ref _approvaluserid, value); } }
    	private int _stockid;
        public int StockID { get { return _stockid; } set { SetNotifyingProperty(ref _stockid, value); } }
    	private Nullable<int> _goodid;
        public Nullable<int> GoodID { get { return _goodid; } set { SetNotifyingProperty(ref _goodid, value); } }
    	private Nullable<int> _orderquantity;
        public Nullable<int> OrderQuantity { get { return _orderquantity; } set { SetNotifyingProperty(ref _orderquantity, value); } }
    	private Nullable<int> _implementquantity;
        public Nullable<int> ImplementQuantity { get { return _implementquantity; } set { SetNotifyingProperty(ref _implementquantity, value); } }
    	private Nullable<int> _remainquantity;
        public Nullable<int> RemainQuantity { get { return _remainquantity; } set { SetNotifyingProperty(ref _remainquantity, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private int _status;
        public int Status { get { return _status; } set { SetNotifyingProperty(ref _status, value); } }
    	private Nullable<int> _type;
        public Nullable<int> Type { get { return _type; } set { SetNotifyingProperty(ref _type, value); } }
    	private string _customerjob;
        public string CustomerJob { get { return _customerjob; } set { SetNotifyingProperty(ref _customerjob, value); } }
    	private Nullable<int> _manufacturingtype;
        public Nullable<int> ManufacturingType { get { return _manufacturingtype; } set { SetNotifyingProperty(ref _manufacturingtype, value); } }
    	private Nullable<int> _companyid;
        public Nullable<int> CompanyID { get { return _companyid; } set { SetNotifyingProperty(ref _companyid, value); } }
    	private Nullable<System.DateTime> _approvaldate;
        public Nullable<System.DateTime> ApprovalDate { get { return _approvaldate; } set { SetNotifyingProperty(ref _approvaldate, value); } }
    
    	private User _user;
        public virtual User User { get { return _user; } set { SetNotifyingProperty(ref _user, value); } }
    	private User _user1;
        public virtual User User1 { get { return _user1; } set { SetNotifyingProperty(ref _user1, value); } }
    	private ICollection<WorkOrderDetail> _workorderdetails;
        public virtual ICollection<WorkOrderDetail> WorkOrderDetails { get { return _workorderdetails; } set { SetNotifyingProperty(ref _workorderdetails, value); } }
    	private Good _good;
        public virtual Good Good { get { return _good; } set { SetNotifyingProperty(ref _good, value); } }
    	private Company _company;
        public virtual Company Company { get { return _company; } set { SetNotifyingProperty(ref _company, value); } }
    	private Stock _stock;
        public virtual Stock Stock { get { return _stock; } set { SetNotifyingProperty(ref _stock, value); } }
    	private ICollection<AllocWO> _allocwoes;
        public virtual ICollection<AllocWO> AllocWOes { get { return _allocwoes; } set { SetNotifyingProperty(ref _allocwoes, value); } }
    }
}
