//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCenter : Entity
    {
        public WorkCenter()
        {
            this.Machines = new HashSet<Machine>();
            this.ProductionMonitors = new HashSet<ProductionMonitor>();
            this.AllocWOes = new HashSet<AllocWO>();
        }
    
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private string _code;
        public string Code { get { return _code; } set { SetNotifyingProperty(ref _code, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    	private Nullable<System.DateTime> _defaultsetuptime;
        public Nullable<System.DateTime> DefaultSetupTime { get { return _defaultsetuptime; } set { SetNotifyingProperty(ref _defaultsetuptime, value); } }
    	private Nullable<int> _maxdailyruntime;
        public Nullable<int> MaxDailyRuntime { get { return _maxdailyruntime; } set { SetNotifyingProperty(ref _maxdailyruntime, value); } }
    	private Nullable<int> _companyid;
        public Nullable<int> CompanyID { get { return _companyid; } set { SetNotifyingProperty(ref _companyid, value); } }
    
    	private ICollection<Machine> _machines;
        public virtual ICollection<Machine> Machines { get { return _machines; } set { SetNotifyingProperty(ref _machines, value); } }
    	private ICollection<ProductionMonitor> _productionmonitors;
        public virtual ICollection<ProductionMonitor> ProductionMonitors { get { return _productionmonitors; } set { SetNotifyingProperty(ref _productionmonitors, value); } }
    	private Company _company;
        public virtual Company Company { get { return _company; } set { SetNotifyingProperty(ref _company, value); } }
    	private ICollection<AllocWO> _allocwoes;
        public virtual ICollection<AllocWO> AllocWOes { get { return _allocwoes; } set { SetNotifyingProperty(ref _allocwoes, value); } }
    }
}
