//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.ERP.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderDetail : Entity
    {
    	private int _id;
        public int ID { get { return _id; } set { SetNotifyingProperty(ref _id, value); } }
    	private int _workorderid;
        public int WorkOrderID { get { return _workorderid; } set { SetNotifyingProperty(ref _workorderid, value); } }
    	private int _goodid;
        public int GoodID { get { return _goodid; } set { SetNotifyingProperty(ref _goodid, value); } }
    	private int _orderquantity;
        public int OrderQuantity { get { return _orderquantity; } set { SetNotifyingProperty(ref _orderquantity, value); } }
    	private Nullable<int> _implementquantity;
        public Nullable<int> ImplementQuantity { get { return _implementquantity; } set { SetNotifyingProperty(ref _implementquantity, value); } }
    	private Nullable<int> _remainquantity;
        public Nullable<int> RemainQuantity { get { return _remainquantity; } set { SetNotifyingProperty(ref _remainquantity, value); } }
    	private string _description;
        public string Description { get { return _description; } set { SetNotifyingProperty(ref _description, value); } }
    
    	private WorkOrder _workorder;
        public virtual WorkOrder WorkOrder { get { return _workorder; } set { SetNotifyingProperty(ref _workorder, value); } }
    	private Good _good;
        public virtual Good Good { get { return _good; } set { SetNotifyingProperty(ref _good, value); } }
    }
}
